// ============================================================
// Rapid Design System — CSS Variables Bridge Utility
// AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
// ============================================================ //

/**
 * Low-level utility for canvas / imperative libraries (Chart.js,
 * Highcharts, D3, etc.) that need resolved token values rather
 * than var() references.
 *
 * Import once, call from any adapter:
 *
 *   import { token, tokens, palette } from "./_css-vars-bridge";
 *
 *   const bg = token("color-surface-base"); // "#ffffff"
 */

/**
 * Read a single Rapid token's computed value.
 * @param name Token key WITHOUT the --rapid- prefix.
 * @param el   Optional reference element (defaults to <html>).
 */
export function token(name: string, el?: Element): string {
  const target = el ?? document.documentElement;
  return getComputedStyle(target).getPropertyValue(`--rapid-${name}`).trim();
}

/**
 * Read multiple tokens in one call.  Returns an object keyed by
 * the input names.
 */
export function tokens(
  names: string[],
  el?: Element,
): Record<string, string> {
  const target = el ?? document.documentElement;
  const styles = getComputedStyle(target);
  const out: Record<string, string> = {};
  for (const n of names) {
    out[n] = styles.getPropertyValue(`--rapid-${n}`).trim();
  }
  return out;
}

/**
 * Returns a ready-to-use colour palette array suitable for chart
 * series, legends, etc.  Order is intentionally high-contrast for
 * accessibility.
 */
export function palette(el?: Element): string[] {
  return [
    token("color-brand-primary", el),
    token("color-status-success", el),
    token("color-status-warning", el),
    token("color-status-danger", el),
    token("color-brand-secondary", el),
    token("color-brand-tertiary", el),
  ];
}

/**
 * Parse a token value as a number (strips "px", "rem", etc.).
 * Useful for canvas APIs that expect numeric dimensions.
 */
export function tokenNumeric(name: string, el?: Element): number {
  return parseFloat(token(name, el)) || 0;
}

/**
 * Subscribes to theme changes (data-theme attribute mutations).
 * The callback fires whenever the resolved token values change,
 * letting canvas libraries re-paint.
 *
 * @returns A cleanup function to disconnect the observer.
 */
export function onThemeChange(callback: () => void): () => void {
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      if (m.attributeName === "data-theme") {
        callback();
        return;
      }
    }
  });

  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["data-theme"],
  });

  return () => observer.disconnect();
}
