// ============================================================
// Rapid Design System — Chart.js Adapter
// AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
// ============================================================ //

/**
 * Integrates Chart.js with the Rapid Design System by:
 *
 *   1. Patching Chart.defaults with Rapid token values
 *   2. Providing a Chart.js plugin that re-reads tokens on theme change
 *   3. Exporting a palette helper for dataset colours
 *
 * Usage:
 *
 *   import Chart from "chart.js/auto";
 *   import { applyRapidDefaults, rapidThemePlugin } from "./chartjs";
 *
 *   applyRapidDefaults(Chart);
 *   Chart.register(rapidThemePlugin);
 *
 *   new Chart(ctx, { type: "bar", data: { ... } });
 */

import { token, tokenNumeric, palette, onThemeChange } from "./_css-vars-bridge";

/**
 * Patches Chart.defaults so every new chart inherits Rapid
 * typography, colours, and grid styling.
 */
export function applyRapidDefaults(Chart: any): void {
  const d = Chart.defaults;

  d.color = token("color-text-primary");
  d.borderColor = token("color-border-default");
  d.backgroundColor = token("color-surface-raised");

  d.font.family = token("font-family-base");
  d.font.size = tokenNumeric("font-size-md");

  d.plugins.title.color = token("color-text-primary");
  d.plugins.title.font = { ...d.plugins.title.font, weight: "600" };

  d.plugins.legend.labels.color = token("color-text-primary");
  d.plugins.tooltip.backgroundColor = token("color-surface-raised");
  d.plugins.tooltip.titleColor = token("color-text-primary");
  d.plugins.tooltip.bodyColor = token("color-text-secondary");
  d.plugins.tooltip.borderColor = token("color-border-default");
  d.plugins.tooltip.borderWidth = 1;
  d.plugins.tooltip.cornerRadius = tokenNumeric("radius-md");

  if (d.scales?.linear) {
    d.scales.linear.grid = { ...d.scales.linear.grid, color: token("color-border-default") };
  }
  if (d.scales?.category) {
    d.scales.category.grid = { ...d.scales.category.grid, color: token("color-border-default") };
  }
}

/**
 * Returns the Rapid colour palette for chart datasets.
 *
 *   const colors = getRapidChartPalette();
 *   datasets: [{ data, backgroundColor: colors }]
 */
export function getRapidChartPalette(): string[] {
  return palette();
}

/**
 * Chart.js plugin that listens for data-theme changes and
 * triggers a re-render so charts stay in sync with the active theme.
 *
 *   Chart.register(rapidThemePlugin);
 */
export const rapidThemePlugin = {
  id: "rapidTheme",

  beforeInit(chart: any): void {
    const cleanup = onThemeChange(() => {
      applyRapidDefaults(chart.constructor);
      chart.update("none");
    });

    (chart as any).__rapidCleanup = cleanup;
  },

  destroy(chart: any): void {
    (chart as any).__rapidCleanup?.();
  },
};
