// ============================================================
// Rapid Design System — Highcharts JS Bridge (Non-Styled Mode)
// AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
// ============================================================ //

/**
 * For Highcharts in the default (non-styled / inline SVG) mode.
 * Reads Rapid CSS variables and pushes them into Highcharts'
 * global options via Highcharts.setOptions().
 *
 * If you use Highcharts Styled Mode instead, use the CSS adapter
 * (highcharts.css) — it's simpler and requires no JS bridge.
 *
 * Usage:
 *
 *   import Highcharts from "highcharts";
 *   import { applyRapidHighchartsTheme } from "./highcharts";
 *
 *   applyRapidHighchartsTheme(Highcharts);
 */

import { token, tokenNumeric, palette, onThemeChange } from "./_css-vars-bridge";

export function buildRapidHighchartsOptions(): Record<string, any> {
  const colors = palette();

  return {
    colors,
    chart: {
      backgroundColor: token("color-surface-base"),
      style: {
        fontFamily: token("font-family-base"),
        color: token("color-text-primary"),
      },
    },
    title: {
      style: {
        color: token("color-text-primary"),
        fontSize: token("font-size-xl"),
        fontWeight: token("font-weight-semibold"),
      },
    },
    subtitle: {
      style: {
        color: token("color-text-secondary"),
        fontSize: token("font-size-md"),
      },
    },
    xAxis: {
      labels: { style: { color: token("color-text-secondary"), fontSize: token("font-size-sm") } },
      title: { style: { color: token("color-text-secondary") } },
      lineColor: token("color-border-default"),
      gridLineColor: token("color-border-default"),
      tickColor: token("color-border-default"),
    },
    yAxis: {
      labels: { style: { color: token("color-text-secondary"), fontSize: token("font-size-sm") } },
      title: { style: { color: token("color-text-secondary") } },
      lineColor: token("color-border-default"),
      gridLineColor: token("color-border-default"),
      tickColor: token("color-border-default"),
    },
    legend: {
      itemStyle: {
        color: token("color-text-primary"),
        fontWeight: token("font-weight-regular"),
        fontSize: token("font-size-sm"),
      },
      itemHoverStyle: { color: token("color-brand-primary") },
    },
    tooltip: {
      backgroundColor: token("color-surface-raised"),
      borderColor: token("color-border-default"),
      style: {
        color: token("color-text-primary"),
        fontSize: token("font-size-sm"),
      },
    },
    plotOptions: {
      series: {
        borderColor: token("color-surface-base"),
      },
    },
    credits: {
      style: { color: token("color-text-secondary") },
    },
    navigation: {
      buttonOptions: {
        symbolStroke: token("color-text-primary"),
        theme: { fill: token("color-surface-base") },
      },
    },
  };
}

/**
 * Apply the Rapid theme to Highcharts globally.
 * Optionally returns a cleanup function for theme-change listening.
 */
export function applyRapidHighchartsTheme(
  Highcharts: any,
  options?: { watchThemeChanges?: boolean },
): (() => void) | void {
  Highcharts.setOptions(buildRapidHighchartsOptions());

  if (options?.watchThemeChanges) {
    return onThemeChange(() => {
      Highcharts.setOptions(buildRapidHighchartsOptions());
    });
  }
}
