// ============================================================
// Rapid Design System — Power Apps PCF Theme Bridge
// AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
// ============================================================ //

/**
 * Bridge utility for Power Apps Component Framework (PCF) controls.
 *
 * PCF controls render inside a container managed by the platform.
 * This bridge ensures Rapid CSS variables are available inside
 * the control's DOM scope, regardless of whether global.css is
 * loaded at the page level.
 *
 * Usage in your PCF control's init() or updateView():
 *
 *   import { injectRapidTheme, readRapidToken } from "./pcf-theme-bridge";
 *
 *   public init(context: ComponentFramework.Context<IInputs>,
 *               container: HTMLDivElement): void {
 *     injectRapidTheme(container);
 *   }
 */

const RAPID_GLOBAL_CSS_ID = "rapid-design-system-tokens";

/**
 * Injects Rapid's global.css into the document if it isn't already
 * present. Also propagates the data-theme attribute from the host
 * page into the control's scope.
 *
 * @param container - The PCF control's container element
 * @param cssHref   - Path or URL to global.css (auto-detected from
 *                    the PCF bundle if omitted)
 */
export function injectRapidTheme(
  container: HTMLElement,
  cssHref?: string,
): void {
  const doc = container.ownerDocument;

  if (!doc.getElementById(RAPID_GLOBAL_CSS_ID)) {
    const link = doc.createElement("link");
    link.id = RAPID_GLOBAL_CSS_ID;
    link.rel = "stylesheet";
    link.href = cssHref ?? detectCSSPath(container);
    doc.head.appendChild(link);
  }

  syncThemeAttribute(doc);
}

/**
 * Reads a single Rapid CSS variable's computed value from the DOM.
 * Useful for imperative rendering (Canvas, SVG) inside a PCF control.
 *
 * @param token - Token key WITHOUT the --rapid- prefix (e.g. "color-brand-primary")
 * @param el    - Reference element for getComputedStyle (defaults to documentElement)
 */
export function readRapidToken(token: string, el?: Element): string {
  const target = el ?? document.documentElement;
  return getComputedStyle(target).getPropertyValue(`--rapid-${token}`).trim();
}

/**
 * Reads multiple tokens in one shot. Returns a plain object
 * keyed by the input token names.
 */
export function readRapidTokens(
  tokens: string[],
  el?: Element,
): Record<string, string> {
  const target = el ?? document.documentElement;
  const styles = getComputedStyle(target);
  const result: Record<string, string> = {};
  for (const t of tokens) {
    result[t] = styles.getPropertyValue(`--rapid-${t}`).trim();
  }
  return result;
}

/**
 * Syncs the active theme to the `data-theme` attribute on both
 * <html> and the control's container, enabling dark mode inside
 * the PCF shadow scope when the host page theme changes.
 */
export function syncThemeAttribute(doc: Document): void {
  const root = doc.documentElement;
  const prefersDark = window.matchMedia?.("(prefers-color-scheme: dark)").matches;
  const currentTheme = root.getAttribute("data-theme");

  if (!currentTheme && prefersDark) {
    root.setAttribute("data-theme", "dark");
  }
}

/**
 * Resolves the path to global.css relative to the PCF control bundle.
 * Falls back to a CDN-friendly path convention.
 */
function detectCSSPath(container: HTMLElement): string {
  const scripts = container.ownerDocument.querySelectorAll("script[src]");
  for (const s of scripts) {
    const src = (s as HTMLScriptElement).src;
    if (src.includes("rapid-design-system") || src.includes("rds")) {
      const base = src.substring(0, src.lastIndexOf("/"));
      return `${base}/global.css`;
    }
  }
  return "global.css";
}
