// ============================================================
// Rapid Design System — Tailwind CSS Preset
// AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
// ============================================================ //

/**
 * Extends Tailwind's theme with Rapid CSS variable references.
 * All utilities (bg-brand-primary, text-surface-base, p-md, etc.)
 * resolve through Rapid's global custom properties, so theme
 * switching works automatically via data-theme.
 *
 * Usage in tailwind.config.js:
 *
 *   const rapidPreset = require("./packages/adapters/tailwind-preset");
 *
 *   module.exports = {
 *     presets: [rapidPreset],
 *     content: ["./src/**/*.{html,js,tsx}"],
 *   };
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "brand": {
          "primary": "var(--rapid-color-brand-primary)",
          "secondary": "var(--rapid-color-brand-secondary)",
          "tertiary": "var(--rapid-color-brand-tertiary)"
        },
        "surface": {
          "base": "var(--rapid-color-surface-base)",
          "raised": "var(--rapid-color-surface-raised)",
          "overlay": "var(--rapid-color-surface-overlay)",
          "disabled": "var(--rapid-color-surface-disabled)"
        },
        "text": {
          "primary": "var(--rapid-color-text-primary)",
          "secondary": "var(--rapid-color-text-secondary)",
          "disabled": "var(--rapid-color-text-disabled)",
          "on-brand": "var(--rapid-color-text-on-brand)",
          "link": "var(--rapid-color-text-link)",
          "link-hover": "var(--rapid-color-text-link-hover)"
        },
        "border": {
          "default": "var(--rapid-color-border-default)",
          "strong": "var(--rapid-color-border-strong)"
        },
        "focus": {
          "ring": "var(--rapid-color-focus-ring)"
        },
        "status": {
          "info": "var(--rapid-color-status-info)",
          "success": "var(--rapid-color-status-success)",
          "warning": "var(--rapid-color-status-warning)",
          "danger": "var(--rapid-color-status-danger)"
        }
      },
      "spacing": {
        "xs": "var(--rapid-spacing-xs)",
        "sm": "var(--rapid-spacing-sm)",
        "md": "var(--rapid-spacing-md)",
        "lg": "var(--rapid-spacing-lg)",
        "xl": "var(--rapid-spacing-xl)",
        "2xl": "var(--rapid-spacing-2xl)"
      },
      "borderRadius": {
        "sm": "var(--rapid-radius-sm)",
        "md": "var(--rapid-radius-md)",
        "lg": "var(--rapid-radius-lg)",
        "xl": "var(--rapid-radius-xl)",
        "round": "var(--rapid-radius-round)"
      },
      "fontSize": {
        "xs": "var(--rapid-font-size-xs)",
        "sm": "var(--rapid-font-size-sm)",
        "md": "var(--rapid-font-size-md)",
        "lg": "var(--rapid-font-size-lg)",
        "xl": "var(--rapid-font-size-xl)",
        "2xl": "var(--rapid-font-size-2xl)"
      },
      "fontWeight": {
        "regular": "var(--rapid-font-weight-regular)",
        "semibold": "var(--rapid-font-weight-semibold)",
        "bold": "var(--rapid-font-weight-bold)"
      },
      "fontFamily": {
        "sans": [
          "var(--rapid-font-family-base)"
        ],
        "mono": [
          "var(--rapid-font-family-mono)"
        ]
      },
      "lineHeight": {
        "tight": "var(--rapid-font-line-height-tight)",
        "normal": "var(--rapid-font-line-height-normal)",
        "relaxed": "var(--rapid-font-line-height-relaxed)"
      },
      "letterSpacing": {
        "tight": "var(--rapid-font-letter-spacing-tight)",
        "normal": "var(--rapid-font-letter-spacing-normal)",
        "wide": "var(--rapid-font-letter-spacing-wide)"
      },
      "boxShadow": {
        "sm": "var(--rapid-shadow-sm)",
        "DEFAULT": "var(--rapid-shadow-md)",
        "md": "var(--rapid-shadow-md)",
        "lg": "var(--rapid-shadow-lg)"
      },
      "opacity": {
        "disabled": "var(--rapid-opacity-disabled)",
        "hover": "var(--rapid-opacity-hover)",
        "subtle": "var(--rapid-opacity-subtle)"
      },
      "zIndex": {
        "dropdown": "var(--rapid-z-dropdown)",
        "sticky": "var(--rapid-z-sticky)",
        "overlay": "var(--rapid-z-overlay)",
        "modal": "var(--rapid-z-modal)",
        "toast": "var(--rapid-z-toast)"
      },
      "transitionDuration": {
        "fast": "var(--rapid-duration-fast)",
        "normal": "var(--rapid-duration-normal)",
        "slow": "var(--rapid-duration-slow)"
      }
    }
  }
};
