// ============================================================
// Rapid Design System — Tailwind CSS Preset
// AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
// ============================================================ //

/**
 * Extends Tailwind's theme with Rapid CSS variable references.
 * All utilities (bg-brand-primary, text-surface-base, p-md, etc.)
 * resolve through Rapid's global custom properties, so theme
 * switching works automatically via data-theme.
 *
 * Usage in tailwind.config.js:
 *
 *   const rapidPreset = require("./packages/adapters/tailwind-preset");
 *
 *   module.exports = {
 *     presets: [rapidPreset],
 *     content: ["./src/**/*.{html,js,tsx}"],
 *   };
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "brand": {
          "primary": "var(--rapid-color-brand-primary)",
          "secondary": "var(--rapid-color-brand-secondary)",
          "tertiary": "var(--rapid-color-brand-tertiary)"
        },
        "surface": {
          "base": "var(--rapid-color-surface-base)",
          "raised": "var(--rapid-color-surface-raised)",
          "overlay": "var(--rapid-color-surface-overlay)"
        },
        "text": {
          "primary": "var(--rapid-color-text-primary)",
          "secondary": "var(--rapid-color-text-secondary)",
          "on-brand": "var(--rapid-color-text-on-brand)"
        },
        "border": {
          "default": "var(--rapid-color-border-default)",
          "strong": "var(--rapid-color-border-strong)"
        },
        "status": {
          "success": "var(--rapid-color-status-success)",
          "warning": "var(--rapid-color-status-warning)",
          "danger": "var(--rapid-color-status-danger)"
        }
      },
      "spacing": {
        "xs": "var(--rapid-spacing-xs)",
        "sm": "var(--rapid-spacing-sm)",
        "md": "var(--rapid-spacing-md)",
        "lg": "var(--rapid-spacing-lg)",
        "xl": "var(--rapid-spacing-xl)",
        "2xl": "var(--rapid-spacing-2xl)"
      },
      "borderRadius": {
        "sm": "var(--rapid-radius-sm)",
        "md": "var(--rapid-radius-md)",
        "lg": "var(--rapid-radius-lg)",
        "xl": "var(--rapid-radius-xl)",
        "round": "var(--rapid-radius-round)"
      },
      "fontSize": {
        "xs": "var(--rapid-font-size-xs)",
        "sm": "var(--rapid-font-size-sm)",
        "md": "var(--rapid-font-size-md)",
        "lg": "var(--rapid-font-size-lg)",
        "xl": "var(--rapid-font-size-xl)",
        "2xl": "var(--rapid-font-size-2xl)"
      },
      "fontFamily": {
        "sans": "var(--rapid-font-family-base)",
        "mono": "var(--rapid-font-family-mono)"
      },
      "boxShadow": {
        "sm": "var(--rapid-shadow-sm)",
        "DEFAULT": "var(--rapid-shadow-md)",
        "md": "var(--rapid-shadow-md)",
        "lg": "var(--rapid-shadow-lg)"
      }
    }
  }
};
