/**
 * Rapid Design System — Console Bridge
 * AUTO-GENERATED by scripts/build-tokens.js
 *
 * Drop this script on any page to get window.rds in the console:
 *
 *   rds.get("color-brand-primary")           // "#0f6cbd"
 *   rds.set("color-brand-primary", "#e74c3c")// instant update
 *   rds.dark()                                // switch to dark mode
 *   rds.light()                               // switch to light mode
 *   rds.list()                                // print all tokens
 *   rds.search("brand")                       // filter tokens
 *   rds.reset()                               // clear all overrides
 *   rds.export()                              // download JSON
 *   rds.diff()                                // show overrides only
 */
(function () {
  "use strict";

  var PREFIX = "--rapid-";
  var root = document.documentElement;

  var catalog = {
    "color-brand-primary": { light: "#0f6cbd", dark: "#479ef5" },
    "color-brand-secondary": { light: "#115ea3", dark: "#62abf5" },
    "color-brand-tertiary": { light: "#0078d4", dark: "#2886de" },
    "color-surface-base": { light: "#ffffff", dark: "#1b1b1b" },
    "color-surface-raised": { light: "#fafafa", dark: "#2d2d2d" },
    "color-surface-overlay": { light: "#f5f5f5", dark: "#383838" },
    "color-surface-disabled": { light: "#f0f0f0", dark: "#2a2a2a" },
    "color-text-primary": { light: "#242424", dark: "#e0e0e0" },
    "color-text-secondary": { light: "#616161", dark: "#adadad" },
    "color-text-disabled": { light: "#a0a0a0", dark: "#5c5c5c" },
    "color-text-on-brand": { light: "#ffffff", dark: "#ffffff" },
    "color-text-link": { light: "#0f6cbd", dark: "#479ef5" },
    "color-text-link-hover": { light: "#115ea3", dark: "#62abf5" },
    "color-border-default": { light: "#d1d1d1", dark: "#484848" },
    "color-border-strong": { light: "#ababab", dark: "#6a6a6a" },
    "color-focus-ring": { light: "#0f6cbd", dark: "#479ef5" },
    "color-status-info": { light: "#0078d4", dark: "#479ef5" },
    "color-status-success": { light: "#0e7a0d", dark: "#54b054" },
    "color-status-warning": { light: "#f7630c", dark: "#f98845" },
    "color-status-danger": { light: "#b10e1c", dark: "#e34e5e" },
    "spacing-xs": { light: "4px", dark: null },
    "spacing-sm": { light: "8px", dark: null },
    "spacing-md": { light: "16px", dark: null },
    "spacing-lg": { light: "24px", dark: null },
    "spacing-xl": { light: "32px", dark: null },
    "spacing-2xl": { light: "48px", dark: null },
    "font-family-base": { light: "'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif", dark: null },
    "font-family-mono": { light: "'Cascadia Code', 'Fira Code', 'Consolas', monospace", dark: null },
    "font-size-xs": { light: "10px", dark: null },
    "font-size-sm": { light: "12px", dark: null },
    "font-size-md": { light: "14px", dark: null },
    "font-size-lg": { light: "18px", dark: null },
    "font-size-xl": { light: "24px", dark: null },
    "font-size-2xl": { light: "32px", dark: null },
    "font-weight-regular": { light: "400", dark: null },
    "font-weight-semibold": { light: "600", dark: null },
    "font-weight-bold": { light: "700", dark: null },
    "font-line-height-tight": { light: "1.2", dark: null },
    "font-line-height-normal": { light: "1.5", dark: null },
    "font-line-height-relaxed": { light: "1.75", dark: null },
    "font-letter-spacing-tight": { light: "-0.02em", dark: null },
    "font-letter-spacing-normal": { light: "0em", dark: null },
    "font-letter-spacing-wide": { light: "0.05em", dark: null },
    "radius-sm": { light: "2px", dark: null },
    "radius-md": { light: "4px", dark: null },
    "radius-lg": { light: "8px", dark: null },
    "radius-xl": { light: "12px", dark: null },
    "radius-round": { light: "9999px", dark: null },
    "border-width-thin": { light: "1px", dark: null },
    "border-width-thick": { light: "2px", dark: null },
    "shadow-sm": { light: "0 1px 2px rgba(0, 0, 0, 0.12)", dark: "0 1px 2px rgba(0, 0, 0, 0.40)" },
    "shadow-md": { light: "0 2px 4px rgba(0, 0, 0, 0.14)", dark: "0 2px 4px rgba(0, 0, 0, 0.44)" },
    "shadow-lg": { light: "0 8px 16px rgba(0, 0, 0, 0.14)", dark: "0 8px 16px rgba(0, 0, 0, 0.44)" },
    "focus-width": { light: "2px", dark: null },
    "focus-offset": { light: "2px", dark: null },
    "opacity-disabled": { light: "0.4", dark: null },
    "opacity-hover": { light: "0.9", dark: null },
    "opacity-subtle": { light: "0.7", dark: null },
    "duration-fast": { light: "100ms", dark: null },
    "duration-normal": { light: "200ms", dark: null },
    "duration-slow": { light: "400ms", dark: null },
    "easing-default": { light: "cubic-bezier(0.4, 0, 0.2, 1)", dark: null },
    "easing-in": { light: "cubic-bezier(0.4, 0, 1, 1)", dark: null },
    "easing-out": { light: "cubic-bezier(0, 0, 0.2, 1)", dark: null },
    "easing-spring": { light: "cubic-bezier(0.175, 0.885, 0.32, 1.275)", dark: null },
    "z-dropdown": { light: "1000", dark: null },
    "z-sticky": { light: "1100", dark: null },
    "z-overlay": { light: "1300", dark: null },
    "z-modal": { light: "1400", dark: null },
    "z-toast": { light: "1500", dark: null }
  };

  function getVal(name) {
    return getComputedStyle(root).getPropertyValue(PREFIX + name).trim();
  }

  var rds = {
    /** Read a token's current computed value. */
    get: function (name) {
      var v = getVal(name);
      if (!v) console.warn("[rds] Unknown token: " + name);
      return v;
    },

    /** Set a token value. Applies instantly to the page. */
    set: function (name, value) {
      root.style.setProperty(PREFIX + name, value);
      console.log("[rds] %c" + PREFIX + name + "%c = %c" + value,
        "color:#888", "color:inherit", "color:" + (value.startsWith("#") ? value : "inherit") + ";font-weight:bold");
      return value;
    },

    /** Remove an override, reverting to the stylesheet value. */
    unset: function (name) {
      root.style.removeProperty(PREFIX + name);
      console.log("[rds] " + PREFIX + name + " → default (" + getVal(name) + ")");
    },

    /** Switch to dark mode. */
    dark: function () {
      root.setAttribute("data-theme", "dark");
      console.log("[rds] Dark mode enabled");
    },

    /** Switch to light mode. */
    light: function () {
      root.removeAttribute("data-theme");
      console.log("[rds] Light mode enabled");
    },

    /** Toggle between light and dark. */
    toggle: function () {
      if (root.getAttribute("data-theme") === "dark") rds.light();
      else rds.dark();
    },

    /** List all tokens with current values. */
    list: function () {
      var entries = [];
      for (var name in catalog) {
        entries.push({ token: PREFIX + name, value: getVal(name) });
      }
      console.table(entries);
      return entries.length + " tokens";
    },

    /** Search tokens by keyword. */
    search: function (query) {
      var q = (query || "").toLowerCase();
      var entries = [];
      for (var name in catalog) {
        if (name.toLowerCase().includes(q)) {
          entries.push({ token: PREFIX + name, value: getVal(name), light: catalog[name].light, dark: catalog[name].dark });
        }
      }
      console.table(entries);
      return entries.length + " match(es)";
    },

    /** Show all active overrides (inline styles set on :root). */
    diff: function () {
      var overrides = [];
      var style = root.style;
      for (var i = 0; i < style.length; i++) {
        var prop = style[i];
        if (prop.startsWith(PREFIX)) {
          overrides.push({ token: prop, override: style.getPropertyValue(prop).trim() });
        }
      }
      if (overrides.length === 0) {
        console.log("[rds] No overrides active");
      } else {
        console.table(overrides);
      }
      return overrides.length + " override(s)";
    },

    /** Remove all inline overrides. */
    reset: function () {
      var removed = 0;
      var toRemove = [];
      var style = root.style;
      for (var i = 0; i < style.length; i++) {
        if (style[i].startsWith(PREFIX)) toRemove.push(style[i]);
      }
      for (var j = 0; j < toRemove.length; j++) {
        style.removeProperty(toRemove[j]);
        removed++;
      }
      console.log("[rds] Cleared " + removed + " override(s)");
    },

    /** Export current palette as nested JSON (tokens/local.json format). */
    export: function () {
      var nested = {};
      for (var name in catalog) {
        var val = getVal(name);
        var parts = name.split("-");
        var cursor = nested;
        for (var i = 0; i < parts.length - 1; i++) {
          if (!cursor[parts[i]]) cursor[parts[i]] = {};
          cursor = cursor[parts[i]];
        }
        cursor[parts[parts.length - 1]] = val;
      }
      var json = JSON.stringify(nested, null, 2);
      var blob = new Blob([json], { type: "application/json" });
      var url = URL.createObjectURL(blob);
      var a = document.createElement("a");
      a.href = url;
      a.download = "local.json";
      a.click();
      URL.revokeObjectURL(url);
      console.log("[rds] Exported " + Object.keys(catalog).length + " tokens as local.json");
    },

    /** Import overrides from any format (nested JSON, flat CSS-var keys, or dot-path keys). */
    import: function (obj) {
      var count = 0;
      function walk(o, prefix) {
        for (var key in o) {
          if (key.startsWith("_")) continue;
          var val = o[key];
          if (typeof val === "object" && val !== null) {
            walk(val, prefix ? prefix + "-" + key : key);
          } else {
            var name;
            if (key.startsWith(PREFIX)) name = key;
            else if (prefix) name = PREFIX + prefix + "-" + key;
            else name = PREFIX + key.replace(/\./g, "-");
            root.style.setProperty(name, val);
            count++;
          }
        }
      }
      var keys = Object.keys(obj);
      if (keys.length > 0 && typeof obj[keys[0]] === "object") {
        walk(obj, "");
      } else if (keys.length > 0 && keys[0].startsWith(PREFIX)) {
        for (var k in obj) { root.style.setProperty(k, obj[k]); count++; }
      } else {
        for (var k in obj) { root.style.setProperty(PREFIX + k.replace(/\./g, "-"), obj[k]); count++; }
      }
      console.log("[rds] Imported " + count + " token(s)");
    },

    /** Print the token catalog with light/dark defaults. */
    catalog: catalog,

    /** Show help. */
    help: function () {
      console.log(
        "%cRapid Design System — Console API%c\n\n" +
        "  rds.get(name)          Read a token\n" +
        "  rds.set(name, value)   Set a token (instant)\n" +
        "  rds.unset(name)        Revert a single token\n" +
        "  rds.dark()             Dark mode\n" +
        "  rds.light()            Light mode\n" +
        "  rds.toggle()           Toggle mode\n" +
        "  rds.list()             Print all tokens\n" +
        "  rds.search(query)      Filter tokens\n" +
        "  rds.diff()             Show overrides\n" +
        "  rds.reset()            Clear all overrides\n" +
        "  rds.export()           Download JSON\n" +
        "  rds.import({...})      Apply overrides from object\n" +
        "  rds.catalog            Token defaults (light/dark)\n\n" +
        "  Token names omit the --rapid- prefix:\n" +
        "  rds.set(\"color-brand-primary\", \"#e74c3c\")\n",
        "font-weight:bold;font-size:13px;color:#0f6cbd",
        "font-weight:normal;font-size:12px;color:inherit"
      );
    }
  };

  window.rds = rds;

  if (typeof console !== "undefined" && console.log) {
    console.log(
      "%c[RDS]%c Console bridge loaded — type %crds.help()%c for commands",
      "background:#0f6cbd;color:#fff;padding:2px 6px;border-radius:3px;font-weight:600",
      "color:inherit",
      "color:#0f6cbd;font-weight:600",
      "color:inherit"
    );
  }
})();
