/* ============================================================
 * Rapid Design System — Fluent UI v9 Theme Adapter
 * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
 * ============================================================ */

import type { Theme } from "@fluentui/react-components";

/**
 * A partial Fluent UI v9 Theme where every value is a CSS var()
 * reference into Rapid's global custom properties. This means
 * theme switching is pure CSS (via data-theme attribute) with
 * zero JS overhead.
 */
export const rapidFluentTheme: Partial<Theme> = {
  colorBrandBackground: "var(--rapid-color-brand-primary)",
  colorBrandBackgroundHover: "var(--rapid-color-brand-secondary)",
  colorBrandBackgroundPressed: "var(--rapid-color-brand-tertiary)",
  colorBrandForegroundOnLight: "var(--rapid-color-brand-primary)",
  colorNeutralBackground1: "var(--rapid-color-surface-base)",
  colorNeutralBackground2: "var(--rapid-color-surface-raised)",
  colorNeutralBackground3: "var(--rapid-color-surface-overlay)",
  colorNeutralForeground1: "var(--rapid-color-text-primary)",
  colorNeutralForeground2: "var(--rapid-color-text-secondary)",
  colorNeutralForegroundOnBrand: "var(--rapid-color-text-on-brand)",
  colorNeutralStroke1: "var(--rapid-color-border-default)",
  colorNeutralStroke2: "var(--rapid-color-border-strong)",
  colorPaletteGreenForeground1: "var(--rapid-color-status-success)",
  colorPaletteYellowForeground1: "var(--rapid-color-status-warning)",
  colorPaletteRedForeground1: "var(--rapid-color-status-danger)",
  borderRadiusSmall: "var(--rapid-radius-sm)",
  borderRadiusMedium: "var(--rapid-radius-md)",
  borderRadiusLarge: "var(--rapid-radius-lg)",
  borderRadiusXLarge: "var(--rapid-radius-xl)",
  borderRadiusCircular: "var(--rapid-radius-round)",
  fontFamilyBase: "var(--rapid-font-family-base)",
  fontFamilyMonospace: "var(--rapid-font-family-mono)",
  fontSizeBase200: "var(--rapid-font-size-xs)",
  fontSizeBase300: "var(--rapid-font-size-sm)",
  fontSizeBase400: "var(--rapid-font-size-md)",
  fontSizeBase500: "var(--rapid-font-size-lg)",
  fontSizeBase600: "var(--rapid-font-size-xl)",
  fontWeightRegular: "var(--rapid-font-weight-regular)",
  fontWeightSemibold: "var(--rapid-font-weight-semibold)",
  fontWeightBold: "var(--rapid-font-weight-bold)",
  spacingHorizontalS: "var(--rapid-spacing-sm)",
  spacingHorizontalM: "var(--rapid-spacing-md)",
  spacingHorizontalL: "var(--rapid-spacing-lg)",
  spacingHorizontalXL: "var(--rapid-spacing-xl)",
  spacingVerticalS: "var(--rapid-spacing-sm)",
  spacingVerticalM: "var(--rapid-spacing-md)",
  spacingVerticalL: "var(--rapid-spacing-lg)",
  spacingVerticalXL: "var(--rapid-spacing-xl)",
  shadow2: "var(--rapid-shadow-sm)",
  shadow4: "var(--rapid-shadow-md)",
  shadow16: "var(--rapid-shadow-lg)",
};

