/* ============================================================
 * Rapid Design System — <RapidFluentProvider>
 * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
 * ============================================================ */

import React from "react";
import { FluentProvider } from "@fluentui/react-components";
import type { FluentProviderProps } from "@fluentui/react-components";
import { rapidFluentTheme } from "./index";

export type RapidFluentProviderProps = Omit<FluentProviderProps, "theme"> & {
  children: React.ReactNode;
};

/**
 * Drop-in replacement for FluentProvider that injects the Rapid
 * theme. Dark mode is driven by the `data-theme` attribute on
 * <html> or <body> — no JS context needed.
 */
export const RapidFluentProvider: React.FC<RapidFluentProviderProps> = ({
  children,
  ...rest
}) => {
  return (
    <FluentProvider theme={rapidFluentTheme as any} {...rest}>
      {children}
    </FluentProvider>
  );
};
