#!/usr/bin/env node

/**
 * Rapid Design System — Token Build Pipeline
 *
 * Single entry point that reads the canonical JSON token files and
 * emits every downstream artefact from a single `npm run build`.
 *
 * Core outputs:
 *   • packages/css/global.css             – :root + [data-theme="dark"] custom properties
 *   • packages/css/utilities.css          – .rapid-* utility classes
 *   • packages/fluent-adapter/index.ts       – Fluent UI v9 theme object → CSS var() refs
 *   • packages/fluent-adapter/Provider.tsx    – <RapidFluentProvider> wrapper (v9)
 *   • packages/fluent-v8-adapter/index.ts     – Fluent UI v8 theme: IPalette + ISemanticColors + IEffects + IFontStyles
 *   • packages/fluent-v8-adapter/Provider.tsx  – <RapidFluentV8Provider> wrapper (v8)
 *
 * CSS Variable Override Adapters (load after library CSS):
 *   • packages/adapters/bootstrap5.css     – Bootstrap 5.3+
 *   • packages/adapters/ag-grid.css        – AG Grid Community / Enterprise
 *   • packages/adapters/fullcalendar.css   – FullCalendar v6
 *   • packages/adapters/telerik-kendo.css  – Telerik Kendo UI
 *   • packages/adapters/sweetalert2.css    – SweetAlert2
 *   • packages/adapters/devextreme.css     – DevExtreme
 *   • packages/adapters/primereact.css     – PrimeReact / PrimeFaces / PrimeVue
 *   • packages/adapters/bryntum.css        – Bryntum Grid / Scheduler / Gantt
 *
 * CSS Class Override Adapters:
 *   • packages/adapters/highcharts.css     – Highcharts Styled Mode (SVG class overrides)
 *
 * Platform Bridge Adapters:
 *   • packages/adapters/spfx.css           – SharePoint Framework theme slots
 *   • packages/adapters/pcf-theme-bridge.ts – Power Apps PCF control bridge
 *
 * JavaScript Bridge Adapters (for canvas / imperative libraries):
 *   • packages/adapters/_css-vars-bridge.ts – Shared utility: read computed Rapid tokens
 *   • packages/adapters/chartjs.ts          – Chart.js defaults + plugin
 *   • packages/adapters/highcharts.ts       – Highcharts.setOptions() bridge (non-styled)
 *
 * Config Presets:
 *   • packages/adapters/tailwind-preset.js  – Tailwind CSS theme preset
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TOKENS_DIR = path.join(ROOT, "tokens");
const CSS_DIR = path.join(ROOT, "packages", "css");
const FLUENT_DIR = path.join(ROOT, "packages", "fluent-adapter");
const FLUENT_V8_DIR = path.join(ROOT, "packages", "fluent-v8-adapter");
const ADAPTERS_DIR = path.join(ROOT, "packages", "adapters");

const PREFIX = "rapid";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJSON(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function flatten(obj, parentKey = "") {
  const entries = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = parentKey ? `${parentKey}-${key}` : key;
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      entries.push(...flatten(value, fullKey));
    } else {
      entries.push([fullKey, value]);
    }
  }
  return entries;
}

function toCSSVar(flatKey) {
  return `--${PREFIX}-${flatKey}`;
}

function v(tokenKey) {
  return `var(${toCSSVar(tokenKey)})`;
}

function fileHeader(title, extra) {
  const lines = [
    `/* ============================================================`,
    ` * Rapid Design System — ${title}`,
    ` * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT`,
  ];
  if (extra) {
    lines.push(` *`);
    for (const line of extra) lines.push(` * ${line}`);
  }
  lines.push(` * ============================================================ */`);
  return lines.join("\n");
}

function emit(filePath, content, label) {
  fs.writeFileSync(filePath, content);
  const rel = path.relative(ROOT, filePath);
  console.log(`[RDS] ✓ ${rel}`);
}

// ═══════════════════════════════════════════════════════════════════════════
//  CORE OUTPUTS
// ═══════════════════════════════════════════════════════════════════════════

// ---------------------------------------------------------------------------
// global.css — :root + [data-theme="dark"]
// ---------------------------------------------------------------------------

function buildGlobalCSS(baseTokens, darkTokens) {
  const baseEntries = flatten(baseTokens);
  const darkEntries = flatten(darkTokens);

  let css = fileHeader("Global CSS Custom Properties") + "\n\n";

  css += `:root {\n`;
  for (const [key, value] of baseEntries) {
    css += `  ${toCSSVar(key)}: ${value};\n`;
  }
  css += `}\n\n`;

  css += `[data-theme="dark"] {\n`;
  for (const [key, value] of darkEntries) {
    css += `  ${toCSSVar(key)}: ${value};\n`;
  }
  css += `}\n`;

  return css;
}

// ---------------------------------------------------------------------------
// utilities.css — .rapid-* utility classes
// ---------------------------------------------------------------------------

function buildUtilitiesCSS(baseTokens) {
  const lines = [fileHeader("Utility Classes"), ""];

  const colorEntries = flatten(baseTokens.color || {}, "color");
  for (const [key] of colorEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const slug = key.replace(/^color-/, "");
    lines.push(`.${PREFIX}-bg-${slug} { background-color: ${varRef}; }`);
    lines.push(`.${PREFIX}-text-${slug} { color: ${varRef}; }`);
  }
  lines.push("");

  const spacingEntries = flatten(baseTokens.spacing || {}, "spacing");
  for (const [key] of spacingEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const slug = key.replace(/^spacing-/, "");
    lines.push(`.${PREFIX}-p-${slug} { padding: ${varRef}; }`);
    lines.push(`.${PREFIX}-m-${slug} { margin: ${varRef}; }`);
    lines.push(`.${PREFIX}-gap-${slug} { gap: ${varRef}; }`);
  }
  lines.push("");

  for (const [key] of flatten(baseTokens.radius || {}, "radius")) {
    const slug = key.replace(/^radius-/, "");
    lines.push(`.${PREFIX}-rounded-${slug} { border-radius: var(${toCSSVar(key)}); }`);
  }
  lines.push("");

  for (const [key] of flatten(baseTokens.shadow || {}, "shadow")) {
    const slug = key.replace(/^shadow-/, "");
    lines.push(`.${PREFIX}-shadow-${slug} { box-shadow: var(${toCSSVar(key)}); }`);
  }
  lines.push("");

  for (const [key] of flatten(baseTokens.font?.size || {}, "font-size")) {
    const slug = key.replace(/^font-size-/, "");
    lines.push(`.${PREFIX}-text-size-${slug} { font-size: var(${toCSSVar(key)}); }`);
  }

  for (const [key] of flatten(baseTokens.font?.weight || {}, "font-weight")) {
    const slug = key.replace(/^font-weight-/, "");
    lines.push(`.${PREFIX}-font-${slug} { font-weight: var(${toCSSVar(key)}); }`);
  }
  lines.push("");

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Fluent UI v9 adapter — index.ts
// ---------------------------------------------------------------------------

function buildFluentAdapter() {
  const map = {
    colorBrandBackground: "color-brand-primary",
    colorBrandBackgroundHover: "color-brand-secondary",
    colorBrandBackgroundPressed: "color-brand-tertiary",
    colorBrandForegroundOnLight: "color-brand-primary",
    colorNeutralBackground1: "color-surface-base",
    colorNeutralBackground2: "color-surface-raised",
    colorNeutralBackground3: "color-surface-overlay",
    colorNeutralForeground1: "color-text-primary",
    colorNeutralForeground2: "color-text-secondary",
    colorNeutralForegroundOnBrand: "color-text-on-brand",
    colorNeutralStroke1: "color-border-default",
    colorNeutralStroke2: "color-border-strong",
    colorPaletteGreenForeground1: "color-status-success",
    colorPaletteYellowForeground1: "color-status-warning",
    colorPaletteRedForeground1: "color-status-danger",
    borderRadiusSmall: "radius-sm",
    borderRadiusMedium: "radius-md",
    borderRadiusLarge: "radius-lg",
    borderRadiusXLarge: "radius-xl",
    borderRadiusCircular: "radius-round",
    fontFamilyBase: "font-family-base",
    fontFamilyMonospace: "font-family-mono",
    fontSizeBase200: "font-size-xs",
    fontSizeBase300: "font-size-sm",
    fontSizeBase400: "font-size-md",
    fontSizeBase500: "font-size-lg",
    fontSizeBase600: "font-size-xl",
    fontWeightRegular: "font-weight-regular",
    fontWeightSemibold: "font-weight-semibold",
    fontWeightBold: "font-weight-bold",
    spacingHorizontalS: "spacing-sm",
    spacingHorizontalM: "spacing-md",
    spacingHorizontalL: "spacing-lg",
    spacingHorizontalXL: "spacing-xl",
    spacingVerticalS: "spacing-sm",
    spacingVerticalM: "spacing-md",
    spacingVerticalL: "spacing-lg",
    spacingVerticalXL: "spacing-xl",
    shadow2: "shadow-sm",
    shadow4: "shadow-md",
    shadow16: "shadow-lg",
  };

  const lines = [
    fileHeader("Fluent UI v9 Theme Adapter"),
    "",
    `import type { Theme } from "@fluentui/react-components";`,
    "",
    "/**",
    " * A partial Fluent UI v9 Theme where every value is a CSS var()",
    " * reference into Rapid's global custom properties. Theme",
    " * switching is pure CSS (via data-theme attribute) with",
    " * zero JS overhead.",
    " */",
    "export const rapidFluentTheme: Partial<Theme> = {",
  ];

  for (const [fluentKey, tokenKey] of Object.entries(map)) {
    lines.push(`  ${fluentKey}: "${v(tokenKey)}",`);
  }

  lines.push("};", "");
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Fluent UI v9 — Provider.tsx
// ---------------------------------------------------------------------------

function buildProviderTSX() {
  return `${fileHeader("<RapidFluentProvider>")}

import React from "react";
import { FluentProvider } from "@fluentui/react-components";
import type { FluentProviderProps } from "@fluentui/react-components";
import { rapidFluentTheme } from "./index";

export type RapidFluentProviderProps = Omit<FluentProviderProps, "theme"> & {
  children: React.ReactNode;
};

/**
 * Drop-in replacement for FluentProvider that injects the Rapid
 * theme. Dark mode is driven by the \`data-theme\` attribute on
 * <html> or <body> — no JS context needed.
 */
export const RapidFluentProvider: React.FC<RapidFluentProviderProps> = ({
  children,
  ...rest
}) => {
  return (
    <FluentProvider theme={rapidFluentTheme as any} {...rest}>
      {children}
    </FluentProvider>
  );
};
`;
}

// ---------------------------------------------------------------------------
// Fluent UI v8 adapter — index.ts
//
// v8 uses createTheme() with IPalette / ISemanticColors / IEffects / IFontStyles.
// Values pass through mergeStyles → CSS, so var() strings resolve in the browser.
// We supply EVERY semantic color explicitly to bypass v8's internal colour
// derivation (which can't parse var() as hex).
// ---------------------------------------------------------------------------

function buildFluentV8Adapter() {
  const lines = [
    fileHeader("Fluent UI v8 Theme Adapter"),
    "",
    `import type { PartialTheme, IEffects, IFontStyles } from "@fluentui/react";`,
    "",
    "/**",
    " * Fluent UI v8 theme where every colour, radius, shadow, and font",
    " * value is a CSS var() reference into Rapid's global custom properties.",
    " *",
    " * Both this v8 theme and the sibling v9 adapter resolve to the SAME",
    " * --rapid-* CSS variables, so v8 and v9 controls rendered on the same",
    " * page stay in perfect visual sync.  Dark mode is driven by the",
    " * data-theme attribute on <html> — no JS context swap required.",
    " *",
    " * IMPORTANT: v8's createTheme() tries to derive semantic colours by",
    " * parsing palette hex values.  Because we pass var() strings, those",
    " * derivations produce warnings.  Every semantic colour slot is",
    " * therefore provided explicitly below, overriding the broken",
    " * derivations.  The resulting CSS is fully correct.",
    " */",
    "",
  ];

  // ---------- palette ----------

  const palette = {
    themePrimary:        "color-brand-primary",
    themeLighterAlt:     "color-surface-overlay",
    themeLighter:        "color-surface-overlay",
    themeLight:          "color-brand-tertiary",
    themeTertiary:       "color-brand-tertiary",
    themeSecondary:      "color-brand-secondary",
    themeDarkAlt:        "color-brand-secondary",
    themeDark:           "color-brand-secondary",
    themeDarker:         "color-brand-tertiary",

    neutralPrimary:      "color-text-primary",
    neutralDark:         "color-text-primary",
    neutralSecondary:    "color-text-secondary",
    neutralSecondaryAlt: "color-text-secondary",
    neutralTertiary:     "color-border-strong",
    neutralTertiaryAlt:  "color-border-default",
    neutralQuaternary:   "color-border-default",
    neutralQuaternaryAlt:"color-surface-overlay",
    neutralLight:        "color-surface-overlay",
    neutralLighter:      "color-surface-raised",
    neutralLighterAlt:   "color-surface-base",

    black:   "color-text-primary",
    white:   "color-surface-base",
    accent:  "color-brand-primary",

    red:        "color-status-danger",
    redDark:    "color-status-danger",
    green:      "color-status-success",
    greenDark:  "color-status-success",
    yellow:     "color-status-warning",
    yellowDark: "color-status-warning",
    yellowLight:"color-status-warning",
    orange:     "color-status-warning",
    orangeLight:"color-status-warning",
    blueMid:    "color-brand-primary",
    blue:       "color-brand-primary",
    blueDark:   "color-brand-secondary",
    blueLight:  "color-brand-tertiary",
    tealDark:   "color-brand-secondary",
    teal:       "color-brand-primary",
    tealLight:  "color-brand-tertiary",
    purpleDark: "color-brand-secondary",
    purple:     "color-brand-primary",
    purpleLight:"color-brand-tertiary",
    magentaDark:"color-brand-secondary",
    magenta:    "color-brand-primary",
    magentaLight:"color-brand-tertiary",
  };

  lines.push("export const rapidFluentV8Palette = {");
  for (const [slot, token] of Object.entries(palette)) {
    lines.push(`  ${slot}: "${v(token)}",`);
  }
  lines.push("} as const;", "");

  // ---------- semanticColors ----------

  const semantic = {
    // Body
    bodyBackground:              "color-surface-base",
    bodyBackgroundHovered:       "color-surface-overlay",
    bodyBackgroundChecked:       "color-surface-overlay",
    bodyFrameBackground:         "color-surface-base",
    bodyFrameDivider:            "color-border-default",
    bodyText:                    "color-text-primary",
    bodyTextChecked:             "color-text-primary",
    bodySubtext:                 "color-text-secondary",
    bodyStandoutBackground:      "color-surface-raised",
    bodyDivider:                 "color-border-default",

    // Disabled
    disabledBackground:          "color-surface-overlay",
    disabledText:                "color-text-secondary",
    disabledSubtext:             "color-border-default",
    disabledBodyText:            "color-text-secondary",
    disabledBodySubtext:         "color-border-default",

    // Focus
    focusBorder:                 "color-brand-primary",

    // Variant borders
    variantBorder:               "color-border-default",
    variantBorderHovered:        "color-border-strong",

    // Default button
    defaultStateBackground:      "color-surface-base",
    buttonBackground:            "color-surface-raised",
    buttonBackgroundHovered:     "color-surface-overlay",
    buttonBackgroundPressed:     "color-surface-overlay",
    buttonBackgroundChecked:     "color-surface-overlay",
    buttonBackgroundCheckedHovered: "color-surface-overlay",
    buttonBackgroundDisabled:    "color-surface-overlay",
    buttonBorder:                "color-border-default",
    buttonBorderDisabled:        "color-border-default",
    buttonText:                  "color-text-primary",
    buttonTextHovered:           "color-text-primary",
    buttonTextPressed:           "color-text-primary",
    buttonTextChecked:           "color-text-primary",
    buttonTextCheckedHovered:    "color-text-primary",
    buttonTextDisabled:          "color-text-secondary",

    // Primary button
    primaryButtonBackground:         "color-brand-primary",
    primaryButtonBackgroundHovered:  "color-brand-secondary",
    primaryButtonBackgroundPressed:  "color-brand-tertiary",
    primaryButtonBackgroundDisabled: "color-surface-overlay",
    primaryButtonBorder:             "color-brand-primary",
    primaryButtonText:               "color-text-on-brand",
    primaryButtonTextHovered:        "color-text-on-brand",
    primaryButtonTextPressed:        "color-text-on-brand",
    primaryButtonTextDisabled:       "color-text-secondary",

    // Action (link-style) button
    actionLink:                  "color-text-primary",
    actionLinkHovered:           "color-text-primary",

    // Link
    link:                        "color-brand-primary",
    linkHovered:                 "color-brand-secondary",

    // Input
    inputBorder:                 "color-border-default",
    inputBorderHovered:          "color-border-strong",
    inputBackground:             "color-surface-base",
    inputBackgroundChecked:      "color-brand-primary",
    inputBackgroundCheckedHovered: "color-brand-secondary",
    inputForegroundChecked:      "color-text-on-brand",
    inputFocusBorderAlt:         "color-brand-primary",
    inputText:                   "color-text-primary",
    inputTextHovered:            "color-text-primary",
    inputPlaceholderText:        "color-text-secondary",
    inputPlaceholderBackgroundChecked: "color-brand-secondary",
    inputIcon:                   "color-brand-primary",
    inputIconHovered:            "color-brand-secondary",
    inputIconDisabled:           "color-text-secondary",

    // Menu
    menuBackground:              "color-surface-base",
    menuDivider:                 "color-border-default",
    menuIcon:                    "color-brand-primary",
    menuHeader:                  "color-brand-primary",
    menuItemBackgroundHovered:   "color-surface-overlay",
    menuItemBackgroundPressed:   "color-surface-overlay",
    menuItemText:                "color-text-primary",
    menuItemTextHovered:         "color-text-primary",

    // List
    listBackground:              "color-surface-base",
    listText:                    "color-text-primary",
    listItemBackgroundHovered:   "color-surface-overlay",
    listItemBackgroundChecked:   "color-surface-overlay",
    listItemBackgroundCheckedHovered: "color-surface-overlay",
    listHeaderBackgroundHovered: "color-surface-overlay",
    listHeaderBackgroundPressed: "color-surface-overlay",

    // Status
    errorText:                   "color-status-danger",
    warningText:                 "color-status-warning",
    successText:                 "color-status-success",
    errorBackground:             "color-status-danger",
    warningBackground:           "color-status-warning",
    successBackground:           "color-status-success",
    warningHighlight:            "color-status-warning",
    blockingBackground:          "color-status-danger",

    // Selection
    accentButtonBackground:      "color-brand-primary",
    accentButtonText:            "color-text-on-brand",
    listTextColor:               "color-text-primary",

    // Card
    cardStandoutBackground:      "color-surface-raised",
    cardShadow:                  "shadow-md",
    cardShadowHovered:           "shadow-lg",
  };

  lines.push("export const rapidFluentV8SemanticColors = {");
  for (const [slot, token] of Object.entries(semantic)) {
    lines.push(`  ${slot}: "${v(token)}",`);
  }
  lines.push("} as const;", "");

  // ---------- effects ----------

  lines.push("export const rapidFluentV8Effects: Partial<IEffects> = {");
  lines.push(`  roundedCorner2: "${v("radius-sm")}",`);
  lines.push(`  roundedCorner4: "${v("radius-md")}",`);
  lines.push(`  roundedCorner6: "${v("radius-lg")}",`);
  lines.push(`  elevation4:  "${v("shadow-sm")}",`);
  lines.push(`  elevation8:  "${v("shadow-md")}",`);
  lines.push(`  elevation16: "${v("shadow-md")}",`);
  lines.push(`  elevation64: "${v("shadow-lg")}",`);
  lines.push("};", "");

  // ---------- fonts ----------

  lines.push("const fontBase = {");
  lines.push(`  fontFamily: "${v("font-family-base")}",`);
  lines.push("};", "");

  const fontMap = {
    tiny:        "font-size-xs",
    xSmall:      "font-size-xs",
    small:       "font-size-sm",
    smallPlus:   "font-size-sm",
    medium:      "font-size-md",
    mediumPlus:  "font-size-md",
    large:       "font-size-lg",
    xLarge:      "font-size-xl",
    xLargePlus:  "font-size-xl",
    xxLarge:     "font-size-2xl",
    xxLargePlus: "font-size-2xl",
    superLarge:  "font-size-2xl",
    mega:        "font-size-2xl",
  };

  lines.push("export const rapidFluentV8Fonts: Partial<IFontStyles> = {");
  for (const [slot, token] of Object.entries(fontMap)) {
    lines.push(`  ${slot}: { ...fontBase, fontSize: "${v(token)}" },`);
  }
  lines.push("};", "");

  // ---------- combined theme ----------

  lines.push("/**");
  lines.push(" * Complete v8 PartialTheme ready for <ThemeProvider> or loadTheme().");
  lines.push(" *");
  lines.push(" * Both v8 and v9 adapters resolve through identical --rapid-* CSS");
  lines.push(" * variables, so a page mixing v8 DetailsList and v9 Button will");
  lines.push(" * render with a single coherent palette and switch themes in unison.");
  lines.push(" */");
  lines.push("export const rapidFluentV8Theme: PartialTheme = {");
  lines.push("  palette: rapidFluentV8Palette as any,");
  lines.push("  semanticColors: rapidFluentV8SemanticColors as any,");
  lines.push("  effects: rapidFluentV8Effects as any,");
  lines.push("  fonts: rapidFluentV8Fonts as any,");
  lines.push("  isInverted: false,");
  lines.push("};", "");

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Fluent UI v8 — Provider.tsx
// ---------------------------------------------------------------------------

function buildFluentV8ProviderTSX() {
  return `${fileHeader("<RapidFluentV8Provider>")}

import React from "react";
import { ThemeProvider, createTheme } from "@fluentui/react";
import type { PartialTheme } from "@fluentui/react";
import { rapidFluentV8Theme } from "./index";

export interface RapidFluentV8ProviderProps {
  children: React.ReactNode;
  /**
   * Optional overrides merged on top of the Rapid v8 theme.
   * Use this for per-section tweaks without breaking the
   * Rapid token contract.
   */
  themeOverrides?: PartialTheme;
  /**
   * When true, applies the theme globally via loadTheme() in
   * addition to the React context.  Useful for legacy code that
   * reads the global theme singleton.
   */
  applyGlobally?: boolean;
}

/**
 * Drop-in Fluent UI v8 ThemeProvider wired to Rapid tokens.
 *
 * Use alongside <RapidFluentProvider> (v9) in the same tree — both
 * resolve through the same --rapid-* CSS variables, so v8 DetailsList
 * and v9 Button stay visually synchronised across light/dark.
 *
 * Dark mode: set \`data-theme="dark"\` on <html>.  No JS context
 * swap is needed; the CSS custom properties update and both
 * v8 and v9 controls repaint in unison.
 *
 * \`\`\`tsx
 * // Mixed v8 + v9 page
 * <RapidFluentV8Provider>
 *   <DetailsList ... />        {/* v8 */}
 *   <RapidFluentProvider>
 *     <Button>Save</Button>    {/* v9 */}
 *   </RapidFluentProvider>
 * </RapidFluentV8Provider>
 * \`\`\`
 */
export const RapidFluentV8Provider: React.FC<RapidFluentV8ProviderProps> = ({
  children,
  themeOverrides,
  applyGlobally = false,
}) => {
  const merged = themeOverrides
    ? createTheme({ ...rapidFluentV8Theme, ...themeOverrides })
    : createTheme(rapidFluentV8Theme);

  if (applyGlobally) {
    // Side-effect: also push to the global singleton so non-React
    // code (loadTheme consumers, mergeStyles) picks it up.
    try {
      const { loadTheme } = require("@fluentui/react");
      loadTheme(merged);
    } catch {
      // loadTheme unavailable — ThemeProvider context is still applied.
    }
  }

  return <ThemeProvider theme={merged}>{children}</ThemeProvider>;
};
`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  CSS VARIABLE OVERRIDE ADAPTERS
//  Load these stylesheets AFTER the target library's own CSS so that
//  the cascade resolves the Rapid var() references.
// ═══════════════════════════════════════════════════════════════════════════

// ---------------------------------------------------------------------------
// Bootstrap 5.3+
// ---------------------------------------------------------------------------

function buildBootstrap5Adapter() {
  return `${fileHeader("Bootstrap 5.3+ Adapter", [
    "Overrides Bootstrap's native CSS custom properties with Rapid",
    "var() references. Load this stylesheet AFTER Bootstrap's CSS.",
    "Dark mode: set data-theme=\"dark\" on <html> — Bootstrap's",
    "[data-bs-theme] attribute is NOT required.",
  ])}

:root,
[data-bs-theme="light"] {
  /* --- Brand / Action --- */
  --bs-primary: ${v("color-brand-primary")};
  --bs-primary-rgb: none;
  --bs-link-color: ${v("color-brand-primary")};
  --bs-link-hover-color: ${v("color-brand-secondary")};

  /* --- Surfaces --- */
  --bs-body-bg: ${v("color-surface-base")};
  --bs-secondary-bg: ${v("color-surface-raised")};
  --bs-tertiary-bg: ${v("color-surface-overlay")};

  /* --- Text --- */
  --bs-body-color: ${v("color-text-primary")};
  --bs-secondary-color: ${v("color-text-secondary")};
  --bs-emphasis-color: ${v("color-text-primary")};
  --bs-heading-color: ${v("color-text-primary")};

  /* --- Borders --- */
  --bs-border-color: ${v("color-border-default")};

  /* --- Status --- */
  --bs-success: ${v("color-status-success")};
  --bs-warning: ${v("color-status-warning")};
  --bs-danger: ${v("color-status-danger")};

  /* --- Typography --- */
  --bs-body-font-family: ${v("font-family-base")};
  --bs-body-font-size: ${v("font-size-md")};
  --bs-font-sans-serif: ${v("font-family-base")};
  --bs-font-monospace: ${v("font-family-mono")};

  /* --- Border Radii --- */
  --bs-border-radius: ${v("radius-md")};
  --bs-border-radius-sm: ${v("radius-sm")};
  --bs-border-radius-lg: ${v("radius-lg")};
  --bs-border-radius-xl: ${v("radius-xl")};
  --bs-border-radius-pill: ${v("radius-round")};

  /* --- Shadows --- */
  --bs-box-shadow: ${v("shadow-md")};
  --bs-box-shadow-sm: ${v("shadow-sm")};
  --bs-box-shadow-lg: ${v("shadow-lg")};
}

[data-bs-theme="dark"] {
  --bs-body-bg: ${v("color-surface-base")};
  --bs-body-color: ${v("color-text-primary")};
  --bs-emphasis-color: ${v("color-text-primary")};
  --bs-secondary-color: ${v("color-text-secondary")};
  --bs-tertiary-bg: ${v("color-surface-overlay")};
  --bs-border-color: ${v("color-border-default")};
}
`;
}

// ---------------------------------------------------------------------------
// AG Grid
// ---------------------------------------------------------------------------

function buildAGGridAdapter() {
  return `${fileHeader("AG Grid Adapter", [
    "Overrides AG Grid's CSS custom properties with Rapid var() references.",
    "Works with Community and Enterprise editions, all bundled themes",
    "(Alpine, Balham, Material, Quartz). Load AFTER ag-grid CSS.",
  ])}

.ag-theme-alpine,
.ag-theme-alpine-dark,
.ag-theme-balham,
.ag-theme-balham-dark,
.ag-theme-material,
.ag-theme-quartz,
.ag-theme-quartz-dark,
:root {
  /* --- Chrome / Surfaces --- */
  --ag-background-color: ${v("color-surface-base")};
  --ag-header-background-color: ${v("color-surface-raised")};
  --ag-control-panel-background-color: ${v("color-surface-raised")};
  --ag-subheader-background-color: ${v("color-surface-overlay")};
  --ag-odd-row-background-color: ${v("color-surface-overlay")};
  --ag-row-hover-color: ${v("color-surface-overlay")};
  --ag-modal-overlay-background-color: ${v("color-surface-overlay")};
  --ag-tooltip-background-color: ${v("color-surface-raised")};

  /* --- Text --- */
  --ag-foreground-color: ${v("color-text-primary")};
  --ag-header-foreground-color: ${v("color-text-primary")};
  --ag-data-color: ${v("color-text-primary")};
  --ag-secondary-foreground-color: ${v("color-text-secondary")};

  /* --- Borders --- */
  --ag-border-color: ${v("color-border-default")};
  --ag-row-border-color: ${v("color-border-default")};
  --ag-secondary-border-color: ${v("color-border-strong")};

  /* --- Selection & Focus --- */
  --ag-selected-row-background-color: ${v("color-brand-primary")};
  --ag-range-selection-background-color: ${v("color-brand-primary")};
  --ag-range-selection-border-color: ${v("color-brand-secondary")};
  --ag-input-focus-border-color: ${v("color-brand-primary")};
  --ag-checkbox-checked-color: ${v("color-brand-primary")};
  --ag-column-hover-color: ${v("color-surface-overlay")};

  /* --- Status --- */
  --ag-invalid-color: ${v("color-status-danger")};

  /* --- Typography --- */
  --ag-font-family: ${v("font-family-base")};
  --ag-font-size: ${v("font-size-md")};

  /* --- Spacing --- */
  --ag-grid-size: ${v("spacing-xs")};
  --ag-cell-horizontal-padding: ${v("spacing-sm")};
  --ag-row-height: calc(${v("spacing-md")} * 2 + ${v("font-size-md")});
  --ag-header-height: calc(${v("spacing-md")} * 2 + ${v("font-size-md")});

  /* --- Borders / Radii --- */
  --ag-border-radius: ${v("radius-md")};
  --ag-card-radius: ${v("radius-lg")};
  --ag-wrapper-border-radius: ${v("radius-md")};

  /* --- Shadows --- */
  --ag-card-shadow: ${v("shadow-md")};
  --ag-popup-shadow: ${v("shadow-lg")};
}
`;
}

// ---------------------------------------------------------------------------
// FullCalendar v6
// ---------------------------------------------------------------------------

function buildFullCalendarAdapter() {
  return `${fileHeader("FullCalendar v6 Adapter", [
    "Overrides FullCalendar's CSS custom properties with Rapid var()",
    "references. Load this stylesheet AFTER FullCalendar's CSS.",
    "Supports all view types (dayGrid, timeGrid, list, multiMonth).",
  ])}

:root {
  /* --- Page / Surfaces --- */
  --fc-page-bg-color: ${v("color-surface-base")};
  --fc-neutral-bg-color: ${v("color-surface-raised")};
  --fc-neutral-text-color: ${v("color-text-secondary")};

  /* --- Borders --- */
  --fc-border-color: ${v("color-border-default")};

  /* --- Buttons (toolbar) --- */
  --fc-button-bg-color: ${v("color-brand-primary")};
  --fc-button-border-color: ${v("color-brand-primary")};
  --fc-button-text-color: ${v("color-text-on-brand")};
  --fc-button-hover-bg-color: ${v("color-brand-secondary")};
  --fc-button-hover-border-color: ${v("color-brand-secondary")};
  --fc-button-active-bg-color: ${v("color-brand-tertiary")};
  --fc-button-active-border-color: ${v("color-brand-tertiary")};

  /* --- Events --- */
  --fc-event-bg-color: ${v("color-brand-primary")};
  --fc-event-border-color: ${v("color-brand-secondary")};
  --fc-event-text-color: ${v("color-text-on-brand")};
  --fc-event-selected-overlay-color: rgba(0, 0, 0, 0.15);

  /* --- Today / Now --- */
  --fc-today-bg-color: ${v("color-surface-overlay")};
  --fc-now-indicator-color: ${v("color-status-danger")};

  /* --- List View --- */
  --fc-list-event-hover-bg-color: ${v("color-surface-overlay")};

  /* --- Day / Non-business --- */
  --fc-non-business-color: ${v("color-surface-overlay")};
  --fc-highlight-color: ${v("color-surface-overlay")};
  --fc-more-link-bg-color: ${v("color-surface-raised")};
  --fc-more-link-text-color: ${v("color-brand-primary")};

  /* --- Typography (applied via descendant selectors) --- */
  --fc-small-font-size: ${v("font-size-sm")};
}

.fc {
  font-family: ${v("font-family-base")};
  font-size: ${v("font-size-md")};
}
`;
}

// ---------------------------------------------------------------------------
// Telerik / Kendo UI
// ---------------------------------------------------------------------------

function buildTelerikKendoAdapter() {
  return `${fileHeader("Telerik / Kendo UI Adapter", [
    "Overrides Kendo UI's --kendo-* CSS custom properties with Rapid",
    "var() references. Compatible with Kendo UI for jQuery, Angular,",
    "React, and Vue. Load AFTER Kendo's theme CSS.",
  ])}

:root {
  /* --- Brand / Primary --- */
  --kendo-color-primary: ${v("color-brand-primary")};
  --kendo-color-primary-hover: ${v("color-brand-secondary")};
  --kendo-color-primary-active: ${v("color-brand-tertiary")};
  --kendo-color-on-primary: ${v("color-text-on-brand")};
  --kendo-color-primary-emphasis: ${v("color-brand-secondary")};

  /* --- Surfaces --- */
  --kendo-color-surface: ${v("color-surface-base")};
  --kendo-color-surface-alt: ${v("color-surface-raised")};
  --kendo-color-app-surface: ${v("color-surface-base")};
  --kendo-color-on-app-surface: ${v("color-text-primary")};
  --kendo-color-base: ${v("color-surface-raised")};
  --kendo-color-on-base: ${v("color-text-primary")};
  --kendo-color-base-hover: ${v("color-surface-overlay")};
  --kendo-color-base-active: ${v("color-surface-overlay")};
  --kendo-color-subtle: ${v("color-text-secondary")};

  /* --- Borders --- */
  --kendo-color-border: ${v("color-border-default")};
  --kendo-color-border-alt: ${v("color-border-strong")};

  /* --- Status --- */
  --kendo-color-success: ${v("color-status-success")};
  --kendo-color-warning: ${v("color-status-warning")};
  --kendo-color-error: ${v("color-status-danger")};

  /* --- Typography --- */
  --kendo-font-family: ${v("font-family-base")};
  --kendo-font-family-monospace: ${v("font-family-mono")};
  --kendo-font-size: ${v("font-size-md")};
  --kendo-font-size-sm: ${v("font-size-sm")};
  --kendo-font-size-lg: ${v("font-size-lg")};

  /* --- Spacing --- */
  --kendo-spacing-1: ${v("spacing-xs")};
  --kendo-spacing-2: ${v("spacing-sm")};
  --kendo-spacing-4: ${v("spacing-md")};
  --kendo-spacing-6: ${v("spacing-lg")};
  --kendo-spacing-8: ${v("spacing-xl")};

  /* --- Border Radii --- */
  --kendo-border-radius-sm: ${v("radius-sm")};
  --kendo-border-radius-md: ${v("radius-md")};
  --kendo-border-radius-lg: ${v("radius-lg")};

  /* --- Shadows --- */
  --kendo-box-shadow-depth-1: ${v("shadow-sm")};
  --kendo-box-shadow-depth-2: ${v("shadow-md")};
  --kendo-box-shadow-depth-3: ${v("shadow-lg")};
}
`;
}

// ---------------------------------------------------------------------------
// SweetAlert2
// ---------------------------------------------------------------------------

function buildSweetAlert2Adapter() {
  return `${fileHeader("SweetAlert2 Adapter", [
    "Overrides SweetAlert2's --swal2-* CSS custom properties with",
    "Rapid var() references. Load AFTER sweetalert2/dist/sweetalert2.css.",
    "Dark mode is inherited automatically from [data-theme=\"dark\"].",
  ])}

:root {
  /* --- Backdrop / Modal --- */
  --swal2-backdrop: rgba(0, 0, 0, 0.4);
  --swal2-background: ${v("color-surface-base")};
  --swal2-color: ${v("color-text-primary")};
  --swal2-title-color: ${v("color-text-primary")};
  --swal2-html-container-color: ${v("color-text-secondary")};

  /* --- Inputs --- */
  --swal2-input-color: ${v("color-text-primary")};
  --swal2-input-background: ${v("color-surface-base")};
  --swal2-input-border-color: ${v("color-border-default")};
  --swal2-input-border-focus-color: ${v("color-brand-primary")};

  /* --- Buttons --- */
  --swal2-confirm-button-background: ${v("color-brand-primary")};
  --swal2-confirm-button-color: ${v("color-text-on-brand")};
  --swal2-confirm-button-border: 0;
  --swal2-deny-button-background: ${v("color-status-danger")};
  --swal2-deny-button-color: ${v("color-text-on-brand")};
  --swal2-cancel-button-background: ${v("color-surface-raised")};
  --swal2-cancel-button-color: ${v("color-text-primary")};

  /* --- Close / Footer --- */
  --swal2-close-button-color: ${v("color-text-secondary")};
  --swal2-close-button-hover-color: ${v("color-status-danger")};
  --swal2-footer-border-color: ${v("color-border-default")};
  --swal2-timer-progress-bar-background: ${v("color-brand-primary")};

  /* --- Toast --- */
  --swal2-toast-background: ${v("color-surface-raised")};
  --swal2-toast-color: ${v("color-text-primary")};
}

.swal2-popup {
  font-family: ${v("font-family-base")};
  font-size: ${v("font-size-md")};
  border-radius: ${v("radius-lg")};
  box-shadow: ${v("shadow-lg")};
}

.swal2-confirm,
.swal2-deny,
.swal2-cancel {
  border-radius: ${v("radius-md")} !important;
  font-weight: ${v("font-weight-semibold")};
}
`;
}

// ---------------------------------------------------------------------------
// DevExtreme
// ---------------------------------------------------------------------------

function buildDevExtremeAdapter() {
  return `${fileHeader("DevExtreme Adapter", [
    "Overrides DevExtreme's CSS custom properties with Rapid var()",
    "references. Compatible with the Generic, Material, and Fluent",
    "themes. Load AFTER the DevExtreme theme CSS.",
  ])}

:root {
  /* --- Brand / Accents --- */
  --dx-color-primary: ${v("color-brand-primary")};
  --dx-color-primary-container: ${v("color-brand-secondary")};
  --dx-color-primary-contrast: ${v("color-text-on-brand")};

  /* --- Surfaces --- */
  --dx-color-bg: ${v("color-surface-base")};
  --dx-color-bg-contrast: ${v("color-text-primary")};
  --dx-color-surface: ${v("color-surface-raised")};

  /* --- Text --- */
  --dx-color-text: ${v("color-text-primary")};
  --dx-color-text-secondary: ${v("color-text-secondary")};

  /* --- Borders --- */
  --dx-color-border: ${v("color-border-default")};

  /* --- Status --- */
  --dx-color-danger: ${v("color-status-danger")};
  --dx-color-success: ${v("color-status-success")};
  --dx-color-warning: ${v("color-status-warning")};

  /* --- Typography --- */
  --dx-font-family: ${v("font-family-base")};
  --dx-font-size: ${v("font-size-md")};
  --dx-font-size-small: ${v("font-size-sm")};
  --dx-font-size-heading: ${v("font-size-xl")};

  /* --- Geometry --- */
  --dx-border-radius: ${v("radius-md")};
  --dx-border-radius-small: ${v("radius-sm")};
  --dx-border-radius-large: ${v("radius-lg")};
}

.dx-widget {
  font-family: ${v("font-family-base")};
}

.dx-card {
  box-shadow: ${v("shadow-md")};
  border-radius: ${v("radius-lg")};
}
`;
}

// ---------------------------------------------------------------------------
// PrimeReact / PrimeFaces / PrimeVue
// ---------------------------------------------------------------------------

function buildPrimeReactAdapter() {
  return `${fileHeader("PrimeReact / PrimeFaces / PrimeVue Adapter", [
    "Overrides the PrimeOne CSS custom properties used by PrimeReact,",
    "PrimeFaces, PrimeVue, and PrimeNG. Compatible with all PrimeOne",
    "themes (Lara, Aura, Nora, etc.). Load AFTER the Prime theme CSS.",
  ])}

:root {
  /* --- Brand / Primary --- */
  --primary-color: ${v("color-brand-primary")};
  --primary-color-text: ${v("color-text-on-brand")};
  --primary-dark-color: ${v("color-brand-secondary")};
  --primary-darker-color: ${v("color-brand-tertiary")};
  --highlight-bg: ${v("color-brand-primary")};
  --highlight-text-color: ${v("color-text-on-brand")};

  /* --- Surfaces --- */
  --surface-ground: ${v("color-surface-base")};
  --surface-section: ${v("color-surface-base")};
  --surface-card: ${v("color-surface-raised")};
  --surface-overlay: ${v("color-surface-overlay")};
  --surface-border: ${v("color-border-default")};
  --surface-hover: ${v("color-surface-overlay")};
  --surface-0: ${v("color-surface-base")};
  --surface-50: ${v("color-surface-base")};
  --surface-100: ${v("color-surface-raised")};
  --surface-200: ${v("color-surface-overlay")};

  /* --- Text --- */
  --text-color: ${v("color-text-primary")};
  --text-color-secondary: ${v("color-text-secondary")};

  /* --- Focus --- */
  --focus-ring: 0 0 0 2px ${v("color-surface-base")}, 0 0 0 4px ${v("color-brand-primary")};
  --maskbg: rgba(0, 0, 0, 0.4);

  /* --- Typography --- */
  --font-family: ${v("font-family-base")};

  /* --- Geometry --- */
  --border-radius: ${v("radius-md")};
  --inline-spacing: ${v("spacing-sm")};
  --surface-border-radius: ${v("radius-md")};
}
`;
}

// ---------------------------------------------------------------------------
// Bryntum Grid / Scheduler / Gantt
// ---------------------------------------------------------------------------

function buildBryntumAdapter() {
  return `${fileHeader("Bryntum Adapter", [
    "Maps Bryntum's internal CSS custom properties to Rapid",
    "variables so the grid inherits the active theme.",
    "Include this stylesheet AFTER Bryntum's own CSS.",
  ])}

.b-theme-material,
.b-theme-classic,
.b-theme-classic-light,
.b-theme-classic-dark,
.b-theme-stockholm,
:root {
  /* --- Surface / Chrome --- */
  --b-grid-header-bg: ${v("color-surface-raised")};
  --b-grid-header-color: ${v("color-text-primary")};
  --b-grid-row-bg: ${v("color-surface-base")};
  --b-grid-row-alt-bg: ${v("color-surface-overlay")};
  --b-grid-cell-color: ${v("color-text-primary")};
  --b-grid-border-color: ${v("color-border-default")};

  /* --- Selection & Focus --- */
  --b-grid-selection-bg: ${v("color-brand-primary")};
  --b-grid-selection-color: ${v("color-text-on-brand")};
  --b-grid-focused-cell-border-color: ${v("color-brand-primary")};

  /* --- Scheduler / Gantt specifics --- */
  --b-sch-event-color: ${v("color-text-on-brand")};
  --b-sch-event-bg: ${v("color-brand-primary")};
  --b-sch-event-selected-bg: ${v("color-brand-secondary")};
  --b-gantt-task-color: ${v("color-brand-primary")};
  --b-gantt-milestone-color: ${v("color-brand-secondary")};

  /* --- Toolbar / Panel --- */
  --b-toolbar-background-color: ${v("color-surface-raised")};
  --b-panel-background-color: ${v("color-surface-base")};
  --b-panel-border-color: ${v("color-border-default")};

  /* --- Typography --- */
  --b-font-family: ${v("font-family-base")};
  --b-font-size: ${v("font-size-md")};

  /* --- Spacing --- */
  --b-grid-cell-padding: ${v("spacing-sm")};

  /* --- Shadows --- */
  --b-panel-shadow: ${v("shadow-md")};
  --b-floating-shadow: ${v("shadow-lg")};
}
`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  CSS CLASS OVERRIDE ADAPTERS
// ═══════════════════════════════════════════════════════════════════════════

// ---------------------------------------------------------------------------
// Highcharts — Styled Mode (CSS)
// ---------------------------------------------------------------------------

function buildHighchartsStyledAdapter() {
  return `${fileHeader("Highcharts Styled Mode Adapter", [
    "Targets Highcharts' SVG CSS classes to apply Rapid tokens.",
    "Requires Highcharts \"styled mode\" (import highcharts/css instead",
    "of the default build). Load this stylesheet AFTER Highcharts CSS.",
    "For non-styled mode, use the JS bridge (highcharts.ts) instead.",
  ])}

:root {
  --rapid-chart-color-0: ${v("color-brand-primary")};
  --rapid-chart-color-1: ${v("color-status-success")};
  --rapid-chart-color-2: ${v("color-status-warning")};
  --rapid-chart-color-3: ${v("color-status-danger")};
  --rapid-chart-color-4: ${v("color-brand-secondary")};
  --rapid-chart-color-5: ${v("color-brand-tertiary")};
}

/* --- Chart Background --- */
.highcharts-background {
  fill: ${v("color-surface-base")};
}

/* --- Title / Subtitle --- */
.highcharts-title {
  fill: ${v("color-text-primary")} !important;
  font-family: ${v("font-family-base")};
  font-size: ${v("font-size-xl")};
  font-weight: ${v("font-weight-semibold")};
}

.highcharts-subtitle {
  fill: ${v("color-text-secondary")} !important;
  font-family: ${v("font-family-base")};
}

/* --- Axis --- */
.highcharts-axis-labels text {
  fill: ${v("color-text-secondary")} !important;
  font-family: ${v("font-family-base")};
  font-size: ${v("font-size-sm")};
}

.highcharts-axis-title {
  fill: ${v("color-text-secondary")} !important;
  font-family: ${v("font-family-base")};
}

.highcharts-axis-line {
  stroke: ${v("color-border-default")};
}

.highcharts-grid-line {
  stroke: ${v("color-border-default")};
}

.highcharts-tick {
  stroke: ${v("color-border-default")};
}

/* --- Series palette --- */
.highcharts-color-0 { fill: var(--rapid-chart-color-0); stroke: var(--rapid-chart-color-0); }
.highcharts-color-1 { fill: var(--rapid-chart-color-1); stroke: var(--rapid-chart-color-1); }
.highcharts-color-2 { fill: var(--rapid-chart-color-2); stroke: var(--rapid-chart-color-2); }
.highcharts-color-3 { fill: var(--rapid-chart-color-3); stroke: var(--rapid-chart-color-3); }
.highcharts-color-4 { fill: var(--rapid-chart-color-4); stroke: var(--rapid-chart-color-4); }
.highcharts-color-5 { fill: var(--rapid-chart-color-5); stroke: var(--rapid-chart-color-5); }

/* --- Legend --- */
.highcharts-legend-item text {
  fill: ${v("color-text-primary")} !important;
  font-family: ${v("font-family-base")};
}

/* --- Tooltip --- */
.highcharts-tooltip-box {
  fill: ${v("color-surface-raised")};
  stroke: ${v("color-border-default")};
}

.highcharts-tooltip text {
  fill: ${v("color-text-primary")} !important;
  font-family: ${v("font-family-base")};
  font-size: ${v("font-size-sm")};
}

/* --- Data Labels --- */
.highcharts-data-label text {
  fill: ${v("color-text-primary")} !important;
  font-family: ${v("font-family-base")};
  font-size: ${v("font-size-sm")};
}

/* --- Credits --- */
.highcharts-credits {
  fill: ${v("color-text-secondary")} !important;
  font-size: ${v("font-size-xs")};
}

/* --- Scrollbar / Navigator --- */
.highcharts-scrollbar-track-background {
  fill: ${v("color-surface-overlay")};
}

.highcharts-scrollbar-button {
  fill: ${v("color-surface-raised")};
  stroke: ${v("color-border-default")};
}
`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  PLATFORM BRIDGE ADAPTERS
// ═══════════════════════════════════════════════════════════════════════════

// ---------------------------------------------------------------------------
// SharePoint Framework (SPFx)
// ---------------------------------------------------------------------------

function buildSPFxAdapter() {
  return `${fileHeader("SharePoint Framework (SPFx) Adapter", [
    "Overrides SPFx theme slots with Rapid var() references so that",
    "SPFx web parts and extensions inherit the Rapid theme.",
    "Load AFTER SharePoint's own theme CSS. Rapid is the authority;",
    "SPFx theme slots become pass-through aliases.",
  ])}

:root {
  /* --- SPFx Semantic Slots → Rapid mapping --- */
  --themePrimary: ${v("color-brand-primary")};
  --themeLighterAlt: ${v("color-surface-overlay")};
  --themeLighter: ${v("color-surface-overlay")};
  --themeLight: ${v("color-brand-tertiary")};
  --themeTertiary: ${v("color-brand-tertiary")};
  --themeSecondary: ${v("color-brand-secondary")};
  --themeDarkAlt: ${v("color-brand-secondary")};
  --themeDark: ${v("color-brand-secondary")};
  --themeDarker: ${v("color-brand-tertiary")};

  /* --- Neutral palette --- */
  --neutralLighterAlt: ${v("color-surface-base")};
  --neutralLighter: ${v("color-surface-raised")};
  --neutralLight: ${v("color-surface-overlay")};
  --neutralQuaternaryAlt: ${v("color-surface-overlay")};
  --neutralQuaternary: ${v("color-border-default")};
  --neutralTertiaryAlt: ${v("color-border-default")};
  --neutralTertiary: ${v("color-border-strong")};
  --neutralSecondary: ${v("color-text-secondary")};
  --neutralPrimaryAlt: ${v("color-text-secondary")};
  --neutralPrimary: ${v("color-text-primary")};
  --neutralDark: ${v("color-text-primary")};
  --black: ${v("color-text-primary")};
  --white: ${v("color-surface-base")};

  /* --- Semantic Mapping --- */
  --bodyBackground: ${v("color-surface-base")};
  --bodyText: ${v("color-text-primary")};
  --bodySubtext: ${v("color-text-secondary")};
  --link: ${v("color-brand-primary")};
  --linkHovered: ${v("color-brand-secondary")};
  --inputBorder: ${v("color-border-default")};
  --inputBorderHovered: ${v("color-border-strong")};
  --inputBackground: ${v("color-surface-base")};
  --inputForeground: ${v("color-text-primary")};
  --inputFocusBorderAlt: ${v("color-brand-primary")};
  --errorText: ${v("color-status-danger")};
  --warningText: ${v("color-status-warning")};
  --successText: ${v("color-status-success")};

  /* --- Typography --- */
  --fontFamily: ${v("font-family-base")};
}
`;
}

// ---------------------------------------------------------------------------
// Power Apps PCF Theme Bridge (TypeScript)
// ---------------------------------------------------------------------------

function buildPCFThemeBridge() {
  return `${fileHeader("Power Apps PCF Theme Bridge").replace(/\/\*/g, "//").replace(/\*\//g, "//").replace(/ \* /g, "// ")}

/**
 * Bridge utility for Power Apps Component Framework (PCF) controls.
 *
 * PCF controls render inside a container managed by the platform.
 * This bridge ensures Rapid CSS variables are available inside
 * the control's DOM scope, regardless of whether global.css is
 * loaded at the page level.
 *
 * Usage in your PCF control's init() or updateView():
 *
 *   import { injectRapidTheme, readRapidToken } from "./pcf-theme-bridge";
 *
 *   public init(context: ComponentFramework.Context<IInputs>,
 *               container: HTMLDivElement): void {
 *     injectRapidTheme(container);
 *   }
 */

const RAPID_GLOBAL_CSS_ID = "rapid-design-system-tokens";

/**
 * Injects Rapid's global.css into the document if it isn't already
 * present. Also propagates the data-theme attribute from the host
 * page into the control's scope.
 *
 * @param container - The PCF control's container element
 * @param cssHref   - Path or URL to global.css (auto-detected from
 *                    the PCF bundle if omitted)
 */
export function injectRapidTheme(
  container: HTMLElement,
  cssHref?: string,
): void {
  const doc = container.ownerDocument;

  if (!doc.getElementById(RAPID_GLOBAL_CSS_ID)) {
    const link = doc.createElement("link");
    link.id = RAPID_GLOBAL_CSS_ID;
    link.rel = "stylesheet";
    link.href = cssHref ?? detectCSSPath(container);
    doc.head.appendChild(link);
  }

  syncThemeAttribute(doc);
}

/**
 * Reads a single Rapid CSS variable's computed value from the DOM.
 * Useful for imperative rendering (Canvas, SVG) inside a PCF control.
 *
 * @param token - Token key WITHOUT the --rapid- prefix (e.g. "color-brand-primary")
 * @param el    - Reference element for getComputedStyle (defaults to documentElement)
 */
export function readRapidToken(token: string, el?: Element): string {
  const target = el ?? document.documentElement;
  return getComputedStyle(target).getPropertyValue(\`--rapid-\${token}\`).trim();
}

/**
 * Reads multiple tokens in one shot. Returns a plain object
 * keyed by the input token names.
 */
export function readRapidTokens(
  tokens: string[],
  el?: Element,
): Record<string, string> {
  const target = el ?? document.documentElement;
  const styles = getComputedStyle(target);
  const result: Record<string, string> = {};
  for (const t of tokens) {
    result[t] = styles.getPropertyValue(\`--rapid-\${t}\`).trim();
  }
  return result;
}

/**
 * Syncs the active theme to the \`data-theme\` attribute on both
 * <html> and the control's container, enabling dark mode inside
 * the PCF shadow scope when the host page theme changes.
 */
export function syncThemeAttribute(doc: Document): void {
  const root = doc.documentElement;
  const prefersDark = window.matchMedia?.("(prefers-color-scheme: dark)").matches;
  const currentTheme = root.getAttribute("data-theme");

  if (!currentTheme && prefersDark) {
    root.setAttribute("data-theme", "dark");
  }
}

/**
 * Resolves the path to global.css relative to the PCF control bundle.
 * Falls back to a CDN-friendly path convention.
 */
function detectCSSPath(container: HTMLElement): string {
  const scripts = container.ownerDocument.querySelectorAll("script[src]");
  for (const s of scripts) {
    const src = (s as HTMLScriptElement).src;
    if (src.includes("rapid-design-system") || src.includes("rds")) {
      const base = src.substring(0, src.lastIndexOf("/"));
      return \`\${base}/global.css\`;
    }
  }
  return "global.css";
}
`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  JAVASCRIPT BRIDGE ADAPTERS
//  For canvas-based and imperative libraries that cannot consume CSS vars
//  directly. These read the computed values at runtime.
// ═══════════════════════════════════════════════════════════════════════════

// ---------------------------------------------------------------------------
// Shared CSS Variables Bridge Utility
// ---------------------------------------------------------------------------

function buildCSSVarsBridge() {
  return `${fileHeader("CSS Variables Bridge Utility").replace(/\/\*/g, "//").replace(/\*\//g, "//").replace(/ \* /g, "// ")}

/**
 * Low-level utility for canvas / imperative libraries (Chart.js,
 * Highcharts, D3, etc.) that need resolved token values rather
 * than var() references.
 *
 * Import once, call from any adapter:
 *
 *   import { token, tokens, palette } from "./_css-vars-bridge";
 *
 *   const bg = token("color-surface-base"); // "#ffffff"
 */

/**
 * Read a single Rapid token's computed value.
 * @param name Token key WITHOUT the --rapid- prefix.
 * @param el   Optional reference element (defaults to <html>).
 */
export function token(name: string, el?: Element): string {
  const target = el ?? document.documentElement;
  return getComputedStyle(target).getPropertyValue(\`--rapid-\${name}\`).trim();
}

/**
 * Read multiple tokens in one call.  Returns an object keyed by
 * the input names.
 */
export function tokens(
  names: string[],
  el?: Element,
): Record<string, string> {
  const target = el ?? document.documentElement;
  const styles = getComputedStyle(target);
  const out: Record<string, string> = {};
  for (const n of names) {
    out[n] = styles.getPropertyValue(\`--rapid-\${n}\`).trim();
  }
  return out;
}

/**
 * Returns a ready-to-use colour palette array suitable for chart
 * series, legends, etc.  Order is intentionally high-contrast for
 * accessibility.
 */
export function palette(el?: Element): string[] {
  return [
    token("color-brand-primary", el),
    token("color-status-success", el),
    token("color-status-warning", el),
    token("color-status-danger", el),
    token("color-brand-secondary", el),
    token("color-brand-tertiary", el),
  ];
}

/**
 * Parse a token value as a number (strips "px", "rem", etc.).
 * Useful for canvas APIs that expect numeric dimensions.
 */
export function tokenNumeric(name: string, el?: Element): number {
  return parseFloat(token(name, el)) || 0;
}

/**
 * Subscribes to theme changes (data-theme attribute mutations).
 * The callback fires whenever the resolved token values change,
 * letting canvas libraries re-paint.
 *
 * @returns A cleanup function to disconnect the observer.
 */
export function onThemeChange(callback: () => void): () => void {
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      if (m.attributeName === "data-theme") {
        callback();
        return;
      }
    }
  });

  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["data-theme"],
  });

  return () => observer.disconnect();
}
`;
}

// ---------------------------------------------------------------------------
// Chart.js Adapter
// ---------------------------------------------------------------------------

function buildChartJSAdapter() {
  return `${fileHeader("Chart.js Adapter").replace(/\/\*/g, "//").replace(/\*\//g, "//").replace(/ \* /g, "// ")}

/**
 * Integrates Chart.js with the Rapid Design System by:
 *
 *   1. Patching Chart.defaults with Rapid token values
 *   2. Providing a Chart.js plugin that re-reads tokens on theme change
 *   3. Exporting a palette helper for dataset colours
 *
 * Usage:
 *
 *   import Chart from "chart.js/auto";
 *   import { applyRapidDefaults, rapidThemePlugin } from "./chartjs";
 *
 *   applyRapidDefaults(Chart);
 *   Chart.register(rapidThemePlugin);
 *
 *   new Chart(ctx, { type: "bar", data: { ... } });
 */

import { token, tokenNumeric, palette, onThemeChange } from "./_css-vars-bridge";

/**
 * Patches Chart.defaults so every new chart inherits Rapid
 * typography, colours, and grid styling.
 */
export function applyRapidDefaults(Chart: any): void {
  const d = Chart.defaults;

  d.color = token("color-text-primary");
  d.borderColor = token("color-border-default");
  d.backgroundColor = token("color-surface-raised");

  d.font.family = token("font-family-base");
  d.font.size = tokenNumeric("font-size-md");

  d.plugins.title.color = token("color-text-primary");
  d.plugins.title.font = { ...d.plugins.title.font, weight: "600" };

  d.plugins.legend.labels.color = token("color-text-primary");
  d.plugins.tooltip.backgroundColor = token("color-surface-raised");
  d.plugins.tooltip.titleColor = token("color-text-primary");
  d.plugins.tooltip.bodyColor = token("color-text-secondary");
  d.plugins.tooltip.borderColor = token("color-border-default");
  d.plugins.tooltip.borderWidth = 1;
  d.plugins.tooltip.cornerRadius = tokenNumeric("radius-md");

  if (d.scales?.linear) {
    d.scales.linear.grid = { ...d.scales.linear.grid, color: token("color-border-default") };
  }
  if (d.scales?.category) {
    d.scales.category.grid = { ...d.scales.category.grid, color: token("color-border-default") };
  }
}

/**
 * Returns the Rapid colour palette for chart datasets.
 *
 *   const colors = getRapidChartPalette();
 *   datasets: [{ data, backgroundColor: colors }]
 */
export function getRapidChartPalette(): string[] {
  return palette();
}

/**
 * Chart.js plugin that listens for data-theme changes and
 * triggers a re-render so charts stay in sync with the active theme.
 *
 *   Chart.register(rapidThemePlugin);
 */
export const rapidThemePlugin = {
  id: "rapidTheme",

  beforeInit(chart: any): void {
    const cleanup = onThemeChange(() => {
      applyRapidDefaults(chart.constructor);
      chart.update("none");
    });

    (chart as any).__rapidCleanup = cleanup;
  },

  destroy(chart: any): void {
    (chart as any).__rapidCleanup?.();
  },
};
`;
}

// ---------------------------------------------------------------------------
// Highcharts JS Bridge (Non-Styled Mode)
// ---------------------------------------------------------------------------

function buildHighchartsJSAdapter() {
  return `${fileHeader("Highcharts JS Bridge (Non-Styled Mode)").replace(/\/\*/g, "//").replace(/\*\//g, "//").replace(/ \* /g, "// ")}

/**
 * For Highcharts in the default (non-styled / inline SVG) mode.
 * Reads Rapid CSS variables and pushes them into Highcharts'
 * global options via Highcharts.setOptions().
 *
 * If you use Highcharts Styled Mode instead, use the CSS adapter
 * (highcharts.css) — it's simpler and requires no JS bridge.
 *
 * Usage:
 *
 *   import Highcharts from "highcharts";
 *   import { applyRapidHighchartsTheme } from "./highcharts";
 *
 *   applyRapidHighchartsTheme(Highcharts);
 */

import { token, tokenNumeric, palette, onThemeChange } from "./_css-vars-bridge";

export function buildRapidHighchartsOptions(): Record<string, any> {
  const colors = palette();

  return {
    colors,
    chart: {
      backgroundColor: token("color-surface-base"),
      style: {
        fontFamily: token("font-family-base"),
        color: token("color-text-primary"),
      },
    },
    title: {
      style: {
        color: token("color-text-primary"),
        fontSize: token("font-size-xl"),
        fontWeight: token("font-weight-semibold"),
      },
    },
    subtitle: {
      style: {
        color: token("color-text-secondary"),
        fontSize: token("font-size-md"),
      },
    },
    xAxis: {
      labels: { style: { color: token("color-text-secondary"), fontSize: token("font-size-sm") } },
      title: { style: { color: token("color-text-secondary") } },
      lineColor: token("color-border-default"),
      gridLineColor: token("color-border-default"),
      tickColor: token("color-border-default"),
    },
    yAxis: {
      labels: { style: { color: token("color-text-secondary"), fontSize: token("font-size-sm") } },
      title: { style: { color: token("color-text-secondary") } },
      lineColor: token("color-border-default"),
      gridLineColor: token("color-border-default"),
      tickColor: token("color-border-default"),
    },
    legend: {
      itemStyle: {
        color: token("color-text-primary"),
        fontWeight: token("font-weight-regular"),
        fontSize: token("font-size-sm"),
      },
      itemHoverStyle: { color: token("color-brand-primary") },
    },
    tooltip: {
      backgroundColor: token("color-surface-raised"),
      borderColor: token("color-border-default"),
      style: {
        color: token("color-text-primary"),
        fontSize: token("font-size-sm"),
      },
    },
    plotOptions: {
      series: {
        borderColor: token("color-surface-base"),
      },
    },
    credits: {
      style: { color: token("color-text-secondary") },
    },
    navigation: {
      buttonOptions: {
        symbolStroke: token("color-text-primary"),
        theme: { fill: token("color-surface-base") },
      },
    },
  };
}

/**
 * Apply the Rapid theme to Highcharts globally.
 * Optionally returns a cleanup function for theme-change listening.
 */
export function applyRapidHighchartsTheme(
  Highcharts: any,
  options?: { watchThemeChanges?: boolean },
): (() => void) | void {
  Highcharts.setOptions(buildRapidHighchartsOptions());

  if (options?.watchThemeChanges) {
    return onThemeChange(() => {
      Highcharts.setOptions(buildRapidHighchartsOptions());
    });
  }
}
`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  CONFIG PRESETS
// ═══════════════════════════════════════════════════════════════════════════

// ---------------------------------------------------------------------------
// Tailwind CSS Preset
// ---------------------------------------------------------------------------

function buildTailwindPreset(baseTokens) {
  const colorEntries = flatten(baseTokens.color || {});
  const spacingEntries = flatten(baseTokens.spacing || {});
  const radiusEntries = flatten(baseTokens.radius || {});
  const fontSizeEntries = flatten(baseTokens.font?.size || {});

  function buildNestedObject(entries, prefix) {
    const obj = {};
    for (const [key] of entries) {
      obj[key] = `var(--${PREFIX}-${prefix ? prefix + "-" : ""}${key})`;
    }
    return obj;
  }

  function colorTree(obj, path = "") {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value === "object" && value !== null) {
        result[key] = colorTree(value, path ? `${path}-${key}` : key);
      } else {
        result[key] = `var(--${PREFIX}-color-${path ? path + "-" : ""}${key})`;
      }
    }
    return result;
  }

  const colors = colorTree(baseTokens.color || {});

  const spacing = {};
  for (const [key] of spacingEntries) {
    spacing[key] = `var(--${PREFIX}-spacing-${key})`;
  }

  const borderRadius = {};
  for (const [key] of radiusEntries) {
    borderRadius[key] = `var(--${PREFIX}-radius-${key})`;
  }

  const fontSize = {};
  for (const [key] of fontSizeEntries) {
    fontSize[key] = `var(--${PREFIX}-font-size-${key})`;
  }

  const preset = {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius,
        fontSize,
        fontFamily: {
          sans: `var(--${PREFIX}-font-family-base)`,
          mono: `var(--${PREFIX}-font-family-mono)`,
        },
        boxShadow: {
          sm: `var(--${PREFIX}-shadow-sm)`,
          DEFAULT: `var(--${PREFIX}-shadow-md)`,
          md: `var(--${PREFIX}-shadow-md)`,
          lg: `var(--${PREFIX}-shadow-lg)`,
        },
      },
    },
  };

  return `${fileHeader("Tailwind CSS Preset").replace(/\/\*/g, "//").replace(/\*\//g, "//").replace(/ \* /g, "// ")}

/**
 * Extends Tailwind's theme with Rapid CSS variable references.
 * All utilities (bg-brand-primary, text-surface-base, p-md, etc.)
 * resolve through Rapid's global custom properties, so theme
 * switching works automatically via data-theme.
 *
 * Usage in tailwind.config.js:
 *
 *   const rapidPreset = require("./packages/adapters/tailwind-preset");
 *
 *   module.exports = {
 *     presets: [rapidPreset],
 *     content: ["./src/**/*.{html,js,tsx}"],
 *   };
 */

/** @type {import('tailwindcss').Config} */
module.exports = ${JSON.stringify(preset, null, 2)};
`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  MAIN
// ═══════════════════════════════════════════════════════════════════════════

function main() {
  console.log("[RDS] Reading token sources…\n");

  const baseTokens = readJSON(path.join(TOKENS_DIR, "base.json"));
  const darkTokens = readJSON(path.join(TOKENS_DIR, "dark.json"));

  ensureDir(CSS_DIR);
  ensureDir(FLUENT_DIR);
  ensureDir(FLUENT_V8_DIR);
  ensureDir(ADAPTERS_DIR);

  // ── Core outputs ──────────────────────────────────────────────────────
  console.log("  Core outputs:");
  emit(path.join(CSS_DIR, "global.css"), buildGlobalCSS(baseTokens, darkTokens));
  emit(path.join(CSS_DIR, "utilities.css"), buildUtilitiesCSS(baseTokens));

  // ── Fluent UI v9 ──────────────────────────────────────────────────────
  console.log("\n  Fluent UI v9 Adapter:");
  emit(path.join(FLUENT_DIR, "index.ts"), buildFluentAdapter());
  emit(path.join(FLUENT_DIR, "Provider.tsx"), buildProviderTSX());

  // ── Fluent UI v8 ──────────────────────────────────────────────────────
  console.log("\n  Fluent UI v8 Adapter:");
  emit(path.join(FLUENT_V8_DIR, "index.ts"), buildFluentV8Adapter());
  emit(path.join(FLUENT_V8_DIR, "Provider.tsx"), buildFluentV8ProviderTSX());

  // ── CSS Variable Override Adapters ────────────────────────────────────
  console.log("\n  CSS Variable Override Adapters:");
  emit(path.join(ADAPTERS_DIR, "bootstrap5.css"), buildBootstrap5Adapter());
  emit(path.join(ADAPTERS_DIR, "ag-grid.css"), buildAGGridAdapter());
  emit(path.join(ADAPTERS_DIR, "fullcalendar.css"), buildFullCalendarAdapter());
  emit(path.join(ADAPTERS_DIR, "telerik-kendo.css"), buildTelerikKendoAdapter());
  emit(path.join(ADAPTERS_DIR, "sweetalert2.css"), buildSweetAlert2Adapter());
  emit(path.join(ADAPTERS_DIR, "devextreme.css"), buildDevExtremeAdapter());
  emit(path.join(ADAPTERS_DIR, "primereact.css"), buildPrimeReactAdapter());
  emit(path.join(ADAPTERS_DIR, "bryntum.css"), buildBryntumAdapter());

  // ── CSS Class Override Adapters ───────────────────────────────────────
  console.log("\n  CSS Class Override Adapters:");
  emit(path.join(ADAPTERS_DIR, "highcharts.css"), buildHighchartsStyledAdapter());

  // ── Platform Bridge Adapters ──────────────────────────────────────────
  console.log("\n  Platform Bridge Adapters:");
  emit(path.join(ADAPTERS_DIR, "spfx.css"), buildSPFxAdapter());
  emit(path.join(ADAPTERS_DIR, "pcf-theme-bridge.ts"), buildPCFThemeBridge());

  // ── JavaScript Bridge Adapters ────────────────────────────────────────
  console.log("\n  JavaScript Bridge Adapters:");
  emit(path.join(ADAPTERS_DIR, "_css-vars-bridge.ts"), buildCSSVarsBridge());
  emit(path.join(ADAPTERS_DIR, "chartjs.ts"), buildChartJSAdapter());
  emit(path.join(ADAPTERS_DIR, "highcharts.ts"), buildHighchartsJSAdapter());

  // ── Config Presets ────────────────────────────────────────────────────
  console.log("\n  Config Presets:");
  emit(path.join(ADAPTERS_DIR, "tailwind-preset.js"), buildTailwindPreset(baseTokens));

  console.log("\n[RDS] Build complete — 21 artefacts generated.\n");
}

main();
