#!/usr/bin/env node

/**
 * Rapid Design System — Token Build Pipeline
 *
 * Single entry point that reads the canonical JSON token files and
 * emits every downstream artefact:
 *   • packages/css/global.css        – :root + [data-theme="dark"] custom properties
 *   • packages/css/utilities.css     – .rapid-* utility classes
 *   • packages/fluent-adapter/index.ts – Fluent UI v9 theme object → CSS var() refs
 *   • packages/adapters/bryntum.css  – Third-party variable mapping template
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TOKENS_DIR = path.join(ROOT, "tokens");
const CSS_DIR = path.join(ROOT, "packages", "css");
const FLUENT_DIR = path.join(ROOT, "packages", "fluent-adapter");
const ADAPTERS_DIR = path.join(ROOT, "packages", "adapters");

const PREFIX = "rapid";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJSON(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

/**
 * Flatten a nested object into { "color-brand-primary": "#0f6cbd", … }
 * Separator between nesting levels is a hyphen.
 */
function flatten(obj, parentKey = "") {
  const entries = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = parentKey ? `${parentKey}-${key}` : key;
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      entries.push(...flatten(value, fullKey));
    } else {
      entries.push([fullKey, value]);
    }
  }
  return entries;
}

/**
 * Convert a flat token key to a CSS custom property name.
 * e.g. "color-brand-primary" → "--rapid-color-brand-primary"
 */
function toCSSVar(flatKey) {
  return `--${PREFIX}-${flatKey}`;
}

/**
 * Convert a flat token key to a camelCase JS identifier.
 * e.g. "color-brand-primary" → "colorBrandPrimary"
 */
function toCamelCase(flatKey) {
  return flatKey.replace(/-([a-z0-9])/g, (_, char) => char.toUpperCase());
}

// ---------------------------------------------------------------------------
// 1. Build global.css — :root + [data-theme="dark"]
// ---------------------------------------------------------------------------

function buildGlobalCSS(baseTokens, darkTokens) {
  const baseEntries = flatten(baseTokens);
  const darkEntries = flatten(darkTokens);

  let css = `/* ============================================================\n`;
  css += ` * Rapid Design System — Global CSS Custom Properties\n`;
  css += ` * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT\n`;
  css += ` * ============================================================ */\n\n`;

  css += `:root {\n`;
  for (const [key, value] of baseEntries) {
    css += `  ${toCSSVar(key)}: ${value};\n`;
  }
  css += `}\n\n`;

  css += `[data-theme="dark"] {\n`;
  for (const [key, value] of darkEntries) {
    css += `  ${toCSSVar(key)}: ${value};\n`;
  }
  css += `}\n`;

  return css;
}

// ---------------------------------------------------------------------------
// 2. Build utilities.css — Lightweight utility classes
// ---------------------------------------------------------------------------

/**
 * Generates a set of utility classes that reference the CSS custom properties.
 * Pattern: .rapid-{category}-{name} { <property>: var(--rapid-…); }
 */
function buildUtilitiesCSS(baseTokens) {
  const lines = [];

  lines.push(`/* ============================================================`);
  lines.push(` * Rapid Design System — Utility Classes`);
  lines.push(` * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT`);
  lines.push(` * ============================================================ */`);
  lines.push(``);

  const colorEntries = flatten(baseTokens.color || {}, "color");
  for (const [key] of colorEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const cls = `${PREFIX}-bg-${key.replace(/^color-/, "")}`;
    lines.push(`.${cls} { background-color: ${varRef}; }`);
    const textCls = `${PREFIX}-text-${key.replace(/^color-/, "")}`;
    lines.push(`.${textCls} { color: ${varRef}; }`);
  }

  lines.push(``);

  const spacingEntries = flatten(baseTokens.spacing || {}, "spacing");
  for (const [key] of spacingEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const shortKey = key.replace(/^spacing-/, "");
    lines.push(`.${PREFIX}-p-${shortKey} { padding: ${varRef}; }`);
    lines.push(`.${PREFIX}-m-${shortKey} { margin: ${varRef}; }`);
    lines.push(`.${PREFIX}-gap-${shortKey} { gap: ${varRef}; }`);
  }

  lines.push(``);

  const radiusEntries = flatten(baseTokens.radius || {}, "radius");
  for (const [key] of radiusEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const shortKey = key.replace(/^radius-/, "");
    lines.push(`.${PREFIX}-rounded-${shortKey} { border-radius: ${varRef}; }`);
  }

  lines.push(``);

  const shadowEntries = flatten(baseTokens.shadow || {}, "shadow");
  for (const [key] of shadowEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const shortKey = key.replace(/^shadow-/, "");
    lines.push(`.${PREFIX}-shadow-${shortKey} { box-shadow: ${varRef}; }`);
  }

  lines.push(``);

  const fontSizeEntries = flatten(baseTokens.font?.size || {}, "font-size");
  for (const [key] of fontSizeEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const shortKey = key.replace(/^font-size-/, "");
    lines.push(`.${PREFIX}-text-size-${shortKey} { font-size: ${varRef}; }`);
  }

  const fontWeightEntries = flatten(baseTokens.font?.weight || {}, "font-weight");
  for (const [key] of fontWeightEntries) {
    const varRef = `var(${toCSSVar(key)})`;
    const shortKey = key.replace(/^font-weight-/, "");
    lines.push(`.${PREFIX}-font-${shortKey} { font-weight: ${varRef}; }`);
  }

  lines.push(``);

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// 3. Build Fluent UI v9 adapter — index.ts
// ---------------------------------------------------------------------------

/**
 * Produces a TypeScript file exporting a `rapidFluentTheme` object whose
 * values are CSS `var()` references, suitable for passing to
 * <FluentProvider theme={rapidFluentTheme}>.
 */
function buildFluentAdapter(baseTokens) {
  const allEntries = flatten(baseTokens);

  const lines = [];
  lines.push(`/* ============================================================`);
  lines.push(` * Rapid Design System — Fluent UI v9 Theme Adapter`);
  lines.push(` * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT`);
  lines.push(` * ============================================================ */`);
  lines.push(``);
  lines.push(`import type { Theme } from "@fluentui/react-components";`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * A partial Fluent UI v9 Theme where every value is a CSS var()`);
  lines.push(` * reference into Rapid's global custom properties. This means`);
  lines.push(` * theme switching is pure CSS (via data-theme attribute) with`);
  lines.push(` * zero JS overhead.`);
  lines.push(` */`);
  lines.push(`export const rapidFluentTheme: Partial<Theme> = {`);

  const fluentMappings = buildFluentMappings(baseTokens);
  for (const [fluentKey, cssVar] of fluentMappings) {
    lines.push(`  ${fluentKey}: "var(${cssVar})",`);
  }

  lines.push(`};`);
  lines.push(``);

  return lines.join("\n") + "\n";
}

/**
 * Maps Rapid token paths to well-known Fluent UI v9 theme token names.
 * Returns an array of [fluentTokenName, cssVarName] pairs.
 */
function buildFluentMappings(baseTokens) {
  const mappings = [];

  const map = {
    colorBrandBackground: "color-brand-primary",
    colorBrandBackgroundHover: "color-brand-secondary",
    colorBrandBackgroundPressed: "color-brand-tertiary",
    colorBrandForegroundOnLight: "color-brand-primary",
    colorNeutralBackground1: "color-surface-base",
    colorNeutralBackground2: "color-surface-raised",
    colorNeutralBackground3: "color-surface-overlay",
    colorNeutralForeground1: "color-text-primary",
    colorNeutralForeground2: "color-text-secondary",
    colorNeutralForegroundOnBrand: "color-text-on-brand",
    colorNeutralStroke1: "color-border-default",
    colorNeutralStroke2: "color-border-strong",
    colorPaletteGreenForeground1: "color-status-success",
    colorPaletteYellowForeground1: "color-status-warning",
    colorPaletteRedForeground1: "color-status-danger",
    borderRadiusSmall: "radius-sm",
    borderRadiusMedium: "radius-md",
    borderRadiusLarge: "radius-lg",
    borderRadiusXLarge: "radius-xl",
    borderRadiusCircular: "radius-round",
    fontFamilyBase: "font-family-base",
    fontFamilyMonospace: "font-family-mono",
    fontSizeBase200: "font-size-xs",
    fontSizeBase300: "font-size-sm",
    fontSizeBase400: "font-size-md",
    fontSizeBase500: "font-size-lg",
    fontSizeBase600: "font-size-xl",
    fontWeightRegular: "font-weight-regular",
    fontWeightSemibold: "font-weight-semibold",
    fontWeightBold: "font-weight-bold",
    spacingHorizontalS: "spacing-sm",
    spacingHorizontalM: "spacing-md",
    spacingHorizontalL: "spacing-lg",
    spacingHorizontalXL: "spacing-xl",
    spacingVerticalS: "spacing-sm",
    spacingVerticalM: "spacing-md",
    spacingVerticalL: "spacing-lg",
    spacingVerticalXL: "spacing-xl",
    shadow2: "shadow-sm",
    shadow4: "shadow-md",
    shadow16: "shadow-lg",
  };

  for (const [fluentKey, tokenKey] of Object.entries(map)) {
    mappings.push([fluentKey, toCSSVar(tokenKey)]);
  }

  return mappings;
}

// ---------------------------------------------------------------------------
// 4. Build Bryntum adapter — bryntum.css
// ---------------------------------------------------------------------------

function buildBryntumAdapter(baseTokens) {
  const lines = [];
  lines.push(`/* ============================================================`);
  lines.push(` * Rapid Design System — Bryntum CSS Variable Adapter`);
  lines.push(` * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT`);
  lines.push(` *`);
  lines.push(` * Maps Bryntum's internal CSS custom properties to Rapid`);
  lines.push(` * variables so the grid inherits the active theme.`);
  lines.push(` * Include this stylesheet AFTER Bryntum's own CSS.`);
  lines.push(` * ============================================================ */`);
  lines.push(``);
  lines.push(`.b-theme-material,`);
  lines.push(`.b-theme-classic,`);
  lines.push(`.b-theme-stockholm,`);
  lines.push(`:root {`);
  lines.push(`  /* Surface / chrome */`);
  lines.push(`  --b-grid-header-bg: var(--rapid-color-surface-raised);`);
  lines.push(`  --b-grid-header-color: var(--rapid-color-text-primary);`);
  lines.push(`  --b-grid-row-bg: var(--rapid-color-surface-base);`);
  lines.push(`  --b-grid-row-alt-bg: var(--rapid-color-surface-overlay);`);
  lines.push(`  --b-grid-cell-color: var(--rapid-color-text-primary);`);
  lines.push(`  --b-grid-border-color: var(--rapid-color-border-default);`);
  lines.push(``);
  lines.push(`  /* Selection & focus */`);
  lines.push(`  --b-grid-selection-bg: var(--rapid-color-brand-primary);`);
  lines.push(`  --b-grid-selection-color: var(--rapid-color-text-on-brand);`);
  lines.push(``);
  lines.push(`  /* Typography */`);
  lines.push(`  --b-font-family: var(--rapid-font-family-base);`);
  lines.push(`  --b-font-size: var(--rapid-font-size-md);`);
  lines.push(``);
  lines.push(`  /* Spacing */`);
  lines.push(`  --b-grid-cell-padding: var(--rapid-spacing-sm);`);
  lines.push(``);
  lines.push(`  /* Shadows */`);
  lines.push(`  --b-panel-shadow: var(--rapid-shadow-md);`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// 5. Build Provider.tsx (static file, not generated from tokens)
// ---------------------------------------------------------------------------

function buildProviderTSX() {
  return `/* ============================================================
 * Rapid Design System — <RapidFluentProvider>
 * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
 * ============================================================ */

import React from "react";
import { FluentProvider } from "@fluentui/react-components";
import type { FluentProviderProps } from "@fluentui/react-components";
import { rapidFluentTheme } from "./index";

export type RapidFluentProviderProps = Omit<FluentProviderProps, "theme"> & {
  children: React.ReactNode;
};

/**
 * Drop-in replacement for FluentProvider that injects the Rapid
 * theme. Dark mode is driven by the \`data-theme\` attribute on
 * <html> or <body> — no JS context needed.
 */
export const RapidFluentProvider: React.FC<RapidFluentProviderProps> = ({
  children,
  ...rest
}) => {
  return (
    <FluentProvider theme={rapidFluentTheme as any} {...rest}>
      {children}
    </FluentProvider>
  );
};
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("[RDS] Reading token sources…");

  const baseTokens = readJSON(path.join(TOKENS_DIR, "base.json"));
  const darkTokens = readJSON(path.join(TOKENS_DIR, "dark.json"));

  ensureDir(CSS_DIR);
  ensureDir(FLUENT_DIR);
  ensureDir(ADAPTERS_DIR);

  // --- global.css ---
  const globalCSS = buildGlobalCSS(baseTokens, darkTokens);
  fs.writeFileSync(path.join(CSS_DIR, "global.css"), globalCSS);
  console.log("[RDS] ✓ packages/css/global.css");

  // --- utilities.css ---
  const utilitiesCSS = buildUtilitiesCSS(baseTokens);
  fs.writeFileSync(path.join(CSS_DIR, "utilities.css"), utilitiesCSS);
  console.log("[RDS] ✓ packages/css/utilities.css");

  // --- fluent-adapter/index.ts ---
  const fluentAdapter = buildFluentAdapter(baseTokens);
  fs.writeFileSync(path.join(FLUENT_DIR, "index.ts"), fluentAdapter);
  console.log("[RDS] ✓ packages/fluent-adapter/index.ts");

  // --- fluent-adapter/Provider.tsx ---
  const providerTSX = buildProviderTSX();
  fs.writeFileSync(path.join(FLUENT_DIR, "Provider.tsx"), providerTSX);
  console.log("[RDS] ✓ packages/fluent-adapter/Provider.tsx");

  // --- adapters/bryntum.css ---
  const bryntumCSS = buildBryntumAdapter(baseTokens);
  fs.writeFileSync(path.join(ADAPTERS_DIR, "bryntum.css"), bryntumCSS);
  console.log("[RDS] ✓ packages/adapters/bryntum.css");

  console.log("[RDS] Build complete.");
}

main();
