/* ============================================================
 * Rapid Design System — Fluent UI v8 Theme Adapter
 * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
 * ============================================================ */

import type { PartialTheme, IEffects, IFontStyles } from "@fluentui/react";

/**
 * Fluent UI v8 theme where every colour, radius, shadow, and font
 * value is a CSS var() reference into Rapid's global custom properties.
 *
 * Both this v8 theme and the sibling v9 adapter resolve to the SAME
 * --rapid-* CSS variables, so v8 and v9 controls rendered on the same
 * page stay in perfect visual sync.  Dark mode is driven by the
 * data-theme attribute on <html> — no JS context swap required.
 *
 * IMPORTANT: v8's createTheme() tries to derive semantic colours by
 * parsing palette hex values.  Because we pass var() strings, those
 * derivations produce warnings.  Every semantic colour slot is
 * therefore provided explicitly below, overriding the broken
 * derivations.  The resulting CSS is fully correct.
 */

export const rapidFluentV8Palette = {
  themePrimary: "var(--rapid-color-brand-primary)",
  themeLighterAlt: "var(--rapid-color-surface-overlay)",
  themeLighter: "var(--rapid-color-surface-overlay)",
  themeLight: "var(--rapid-color-brand-tertiary)",
  themeTertiary: "var(--rapid-color-brand-tertiary)",
  themeSecondary: "var(--rapid-color-brand-secondary)",
  themeDarkAlt: "var(--rapid-color-brand-secondary)",
  themeDark: "var(--rapid-color-brand-secondary)",
  themeDarker: "var(--rapid-color-brand-tertiary)",
  neutralPrimary: "var(--rapid-color-text-primary)",
  neutralDark: "var(--rapid-color-text-primary)",
  neutralSecondary: "var(--rapid-color-text-secondary)",
  neutralSecondaryAlt: "var(--rapid-color-text-secondary)",
  neutralTertiary: "var(--rapid-color-border-strong)",
  neutralTertiaryAlt: "var(--rapid-color-border-default)",
  neutralQuaternary: "var(--rapid-color-border-default)",
  neutralQuaternaryAlt: "var(--rapid-color-surface-overlay)",
  neutralLight: "var(--rapid-color-surface-overlay)",
  neutralLighter: "var(--rapid-color-surface-raised)",
  neutralLighterAlt: "var(--rapid-color-surface-base)",
  black: "var(--rapid-color-text-primary)",
  white: "var(--rapid-color-surface-base)",
  accent: "var(--rapid-color-brand-primary)",
  red: "var(--rapid-color-status-danger)",
  redDark: "var(--rapid-color-status-danger)",
  green: "var(--rapid-color-status-success)",
  greenDark: "var(--rapid-color-status-success)",
  yellow: "var(--rapid-color-status-warning)",
  yellowDark: "var(--rapid-color-status-warning)",
  yellowLight: "var(--rapid-color-status-warning)",
  orange: "var(--rapid-color-status-warning)",
  orangeLight: "var(--rapid-color-status-warning)",
  blueMid: "var(--rapid-color-brand-primary)",
  blue: "var(--rapid-color-brand-primary)",
  blueDark: "var(--rapid-color-brand-secondary)",
  blueLight: "var(--rapid-color-brand-tertiary)",
  tealDark: "var(--rapid-color-brand-secondary)",
  teal: "var(--rapid-color-brand-primary)",
  tealLight: "var(--rapid-color-brand-tertiary)",
  purpleDark: "var(--rapid-color-brand-secondary)",
  purple: "var(--rapid-color-brand-primary)",
  purpleLight: "var(--rapid-color-brand-tertiary)",
  magentaDark: "var(--rapid-color-brand-secondary)",
  magenta: "var(--rapid-color-brand-primary)",
  magentaLight: "var(--rapid-color-brand-tertiary)",
} as const;

export const rapidFluentV8SemanticColors = {
  bodyBackground: "var(--rapid-color-surface-base)",
  bodyBackgroundHovered: "var(--rapid-color-surface-overlay)",
  bodyBackgroundChecked: "var(--rapid-color-surface-overlay)",
  bodyFrameBackground: "var(--rapid-color-surface-base)",
  bodyFrameDivider: "var(--rapid-color-border-default)",
  bodyText: "var(--rapid-color-text-primary)",
  bodyTextChecked: "var(--rapid-color-text-primary)",
  bodySubtext: "var(--rapid-color-text-secondary)",
  bodyStandoutBackground: "var(--rapid-color-surface-raised)",
  bodyDivider: "var(--rapid-color-border-default)",
  disabledBackground: "var(--rapid-color-surface-overlay)",
  disabledText: "var(--rapid-color-text-secondary)",
  disabledSubtext: "var(--rapid-color-border-default)",
  disabledBodyText: "var(--rapid-color-text-secondary)",
  disabledBodySubtext: "var(--rapid-color-border-default)",
  focusBorder: "var(--rapid-color-brand-primary)",
  variantBorder: "var(--rapid-color-border-default)",
  variantBorderHovered: "var(--rapid-color-border-strong)",
  defaultStateBackground: "var(--rapid-color-surface-base)",
  buttonBackground: "var(--rapid-color-surface-raised)",
  buttonBackgroundHovered: "var(--rapid-color-surface-overlay)",
  buttonBackgroundPressed: "var(--rapid-color-surface-overlay)",
  buttonBackgroundChecked: "var(--rapid-color-surface-overlay)",
  buttonBackgroundCheckedHovered: "var(--rapid-color-surface-overlay)",
  buttonBackgroundDisabled: "var(--rapid-color-surface-overlay)",
  buttonBorder: "var(--rapid-color-border-default)",
  buttonBorderDisabled: "var(--rapid-color-border-default)",
  buttonText: "var(--rapid-color-text-primary)",
  buttonTextHovered: "var(--rapid-color-text-primary)",
  buttonTextPressed: "var(--rapid-color-text-primary)",
  buttonTextChecked: "var(--rapid-color-text-primary)",
  buttonTextCheckedHovered: "var(--rapid-color-text-primary)",
  buttonTextDisabled: "var(--rapid-color-text-secondary)",
  primaryButtonBackground: "var(--rapid-color-brand-primary)",
  primaryButtonBackgroundHovered: "var(--rapid-color-brand-secondary)",
  primaryButtonBackgroundPressed: "var(--rapid-color-brand-tertiary)",
  primaryButtonBackgroundDisabled: "var(--rapid-color-surface-overlay)",
  primaryButtonBorder: "var(--rapid-color-brand-primary)",
  primaryButtonText: "var(--rapid-color-text-on-brand)",
  primaryButtonTextHovered: "var(--rapid-color-text-on-brand)",
  primaryButtonTextPressed: "var(--rapid-color-text-on-brand)",
  primaryButtonTextDisabled: "var(--rapid-color-text-secondary)",
  actionLink: "var(--rapid-color-text-primary)",
  actionLinkHovered: "var(--rapid-color-text-primary)",
  link: "var(--rapid-color-brand-primary)",
  linkHovered: "var(--rapid-color-brand-secondary)",
  inputBorder: "var(--rapid-color-border-default)",
  inputBorderHovered: "var(--rapid-color-border-strong)",
  inputBackground: "var(--rapid-color-surface-base)",
  inputBackgroundChecked: "var(--rapid-color-brand-primary)",
  inputBackgroundCheckedHovered: "var(--rapid-color-brand-secondary)",
  inputForegroundChecked: "var(--rapid-color-text-on-brand)",
  inputFocusBorderAlt: "var(--rapid-color-brand-primary)",
  inputText: "var(--rapid-color-text-primary)",
  inputTextHovered: "var(--rapid-color-text-primary)",
  inputPlaceholderText: "var(--rapid-color-text-secondary)",
  inputPlaceholderBackgroundChecked: "var(--rapid-color-brand-secondary)",
  inputIcon: "var(--rapid-color-brand-primary)",
  inputIconHovered: "var(--rapid-color-brand-secondary)",
  inputIconDisabled: "var(--rapid-color-text-secondary)",
  menuBackground: "var(--rapid-color-surface-base)",
  menuDivider: "var(--rapid-color-border-default)",
  menuIcon: "var(--rapid-color-brand-primary)",
  menuHeader: "var(--rapid-color-brand-primary)",
  menuItemBackgroundHovered: "var(--rapid-color-surface-overlay)",
  menuItemBackgroundPressed: "var(--rapid-color-surface-overlay)",
  menuItemText: "var(--rapid-color-text-primary)",
  menuItemTextHovered: "var(--rapid-color-text-primary)",
  listBackground: "var(--rapid-color-surface-base)",
  listText: "var(--rapid-color-text-primary)",
  listItemBackgroundHovered: "var(--rapid-color-surface-overlay)",
  listItemBackgroundChecked: "var(--rapid-color-surface-overlay)",
  listItemBackgroundCheckedHovered: "var(--rapid-color-surface-overlay)",
  listHeaderBackgroundHovered: "var(--rapid-color-surface-overlay)",
  listHeaderBackgroundPressed: "var(--rapid-color-surface-overlay)",
  errorText: "var(--rapid-color-status-danger)",
  warningText: "var(--rapid-color-status-warning)",
  successText: "var(--rapid-color-status-success)",
  errorBackground: "var(--rapid-color-status-danger)",
  warningBackground: "var(--rapid-color-status-warning)",
  successBackground: "var(--rapid-color-status-success)",
  warningHighlight: "var(--rapid-color-status-warning)",
  blockingBackground: "var(--rapid-color-status-danger)",
  accentButtonBackground: "var(--rapid-color-brand-primary)",
  accentButtonText: "var(--rapid-color-text-on-brand)",
  listTextColor: "var(--rapid-color-text-primary)",
  cardStandoutBackground: "var(--rapid-color-surface-raised)",
  cardShadow: "var(--rapid-shadow-md)",
  cardShadowHovered: "var(--rapid-shadow-lg)",
} as const;

export const rapidFluentV8Effects: Partial<IEffects> = {
  roundedCorner2: "var(--rapid-radius-sm)",
  roundedCorner4: "var(--rapid-radius-md)",
  roundedCorner6: "var(--rapid-radius-lg)",
  elevation4:  "var(--rapid-shadow-sm)",
  elevation8:  "var(--rapid-shadow-md)",
  elevation16: "var(--rapid-shadow-md)",
  elevation64: "var(--rapid-shadow-lg)",
};

const fontBase = {
  fontFamily: "var(--rapid-font-family-base)",
};

export const rapidFluentV8Fonts: Partial<IFontStyles> = {
  tiny: { ...fontBase, fontSize: "var(--rapid-font-size-xs)" },
  xSmall: { ...fontBase, fontSize: "var(--rapid-font-size-xs)" },
  small: { ...fontBase, fontSize: "var(--rapid-font-size-sm)" },
  smallPlus: { ...fontBase, fontSize: "var(--rapid-font-size-sm)" },
  medium: { ...fontBase, fontSize: "var(--rapid-font-size-md)" },
  mediumPlus: { ...fontBase, fontSize: "var(--rapid-font-size-md)" },
  large: { ...fontBase, fontSize: "var(--rapid-font-size-lg)" },
  xLarge: { ...fontBase, fontSize: "var(--rapid-font-size-xl)" },
  xLargePlus: { ...fontBase, fontSize: "var(--rapid-font-size-xl)" },
  xxLarge: { ...fontBase, fontSize: "var(--rapid-font-size-2xl)" },
  xxLargePlus: { ...fontBase, fontSize: "var(--rapid-font-size-2xl)" },
  superLarge: { ...fontBase, fontSize: "var(--rapid-font-size-2xl)" },
  mega: { ...fontBase, fontSize: "var(--rapid-font-size-2xl)" },
};

/**
 * Complete v8 PartialTheme ready for <ThemeProvider> or loadTheme().
 *
 * Both v8 and v9 adapters resolve through identical --rapid-* CSS
 * variables, so a page mixing v8 DetailsList and v9 Button will
 * render with a single coherent palette and switch themes in unison.
 */
export const rapidFluentV8Theme: PartialTheme = {
  palette: rapidFluentV8Palette as any,
  semanticColors: rapidFluentV8SemanticColors as any,
  effects: rapidFluentV8Effects as any,
  fonts: rapidFluentV8Fonts as any,
  isInverted: false,
};

