/* ============================================================
 * Rapid Design System — <RapidFluentV8Provider>
 * AUTO-GENERATED by scripts/build-tokens.js — DO NOT EDIT
 * ============================================================ */

import React from "react";
import { ThemeProvider, createTheme } from "@fluentui/react";
import type { PartialTheme } from "@fluentui/react";
import { rapidFluentV8Theme } from "./index";

export interface RapidFluentV8ProviderProps {
  children: React.ReactNode;
  /**
   * Optional overrides merged on top of the Rapid v8 theme.
   * Use this for per-section tweaks without breaking the
   * Rapid token contract.
   */
  themeOverrides?: PartialTheme;
  /**
   * When true, applies the theme globally via loadTheme() in
   * addition to the React context.  Useful for legacy code that
   * reads the global theme singleton.
   */
  applyGlobally?: boolean;
}

/**
 * Drop-in Fluent UI v8 ThemeProvider wired to Rapid tokens.
 *
 * Use alongside <RapidFluentProvider> (v9) in the same tree — both
 * resolve through the same --rapid-* CSS variables, so v8 DetailsList
 * and v9 Button stay visually synchronised across light/dark.
 *
 * Dark mode: set `data-theme="dark"` on <html>.  No JS context
 * swap is needed; the CSS custom properties update and both
 * v8 and v9 controls repaint in unison.
 *
 * ```tsx
 * // Mixed v8 + v9 page
 * <RapidFluentV8Provider>
 *   <DetailsList ... />        {/* v8 */}
 *   <RapidFluentProvider>
 *     <Button>Save</Button>    {/* v9 */}
 *   </RapidFluentProvider>
 * </RapidFluentV8Provider>
 * ```
 */
export const RapidFluentV8Provider: React.FC<RapidFluentV8ProviderProps> = ({
  children,
  themeOverrides,
  applyGlobally = false,
}) => {
  const merged = themeOverrides
    ? createTheme({ ...rapidFluentV8Theme, ...themeOverrides })
    : createTheme(rapidFluentV8Theme);

  if (applyGlobally) {
    // Side-effect: also push to the global singleton so non-React
    // code (loadTheme consumers, mergeStyles) picks it up.
    try {
      const { loadTheme } = require("@fluentui/react");
      loadTheme(merged);
    } catch {
      // loadTheme unavailable — ThemeProvider context is still applied.
    }
  }

  return <ThemeProvider theme={merged}>{children}</ThemeProvider>;
};
